### ISSUE TITLE
Onboarding new Spanish translators

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#109]
Hello @msaavedra1026 & @18HopeCSF! Welcome to the Nextstrain Translators group :) We're really happy to have you. Thank you so much for your help!

I've sent you both invitations to join the Nextstrain organization, specifically the Translators and Spanish team. Please accept that invitation. Once you do so, you'll have access to the Spanish discussion page and the ability to edit the appropriate files. This [forum post](https://github.community/t5/How-to-use-Git-and-GitHub/Where-do-I-see-all-incoming-invitations-collaborator/td-p/4280) has helped others troubleshoot finding their invitations. But if you can't find the invitation, just let me know. 

Every week when a report is ready to be translated (Friday afternoon PDT), I make a GitHub issue and will tag you in it. That issue contains the location and link to the file to translate. It also contains a link to preview the translation in the "narratives format". If you're familiar with command line and GitHub, I'd recommend cloning this repository, translating on your local computer, and then pushing up your translation to GitHub on the `sit-rep_es` branch. If you're not familiar with GitHub, you can translate at the online link directly, but if you do so, save your work often to prevent merge conflicts and overwriting by others.

Since neither of you have a technical background in phylogenetics, it would be great if you two can tag team the first draft of the translation. Ideally, this is finished by sometime on Saturday. Then the phylogenetics folks can proofread and review the translation, and we publish it!

If you have Twitter handles, please send me those. We make a Twitter post once the translation is online and like to tag translators in it.

Thank you so much! Please don't hesitate to ask any questions.

@sofiamuller93, if you'd still like to help out, we'd love to have you! Just let me know, and I'll give you the same access as above.

**Comment by ghost** [comment]
Hi @cassiawag! Just started checking this and trying to learn how all this works... I already translated some minor things to see how it goes, let me know if you see something.

**Comment by Cholokiwi** [comment]
Hi Claudio,
Welcome to the team! It looks good. The format is very similar each week so
you could use the previous reports in Spanish as an example, specially for
words or phrases, so you don't have to start from scratch. See report from
last week below.

https://nextstrain.org/narratives/ncov/sit-rep/es/2020-04-24?f_region=Africa

We also usually split the translation in two so you don't have to translate
the whole report yourself. I could do the proofreading after it's been
translated.

Cheers,

Roy

**Comment by cassiawag** [comment]
Glad you were able to get started @18HopeCSF! I think Roy's suggestions are a great place to start; thanks for joining us!
