### ISSUE TITLE
Translate April 3 COVID-19 report into Mandarin Chinese

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#12]
Hello @fillorkill @alvinxhan @lxy0107 @fzhang12 !
 
The situation report from 2020-04-03  is ready to be translated to Mandarin. 
Branch to translate on: `sit-rep_zh` 
File to translate: https://github.com/nextstrain/translations/blob/sit-rep_zh/narratives/translations_ncov_sit-rep_zh_2020-04-03.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!
Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_zh/ncov/sit-rep/zh/2020-04-03
 
**Logistics**
Once you’ve accepted my invitation to join the Nextstrain organization and the `translations` repo, you should have access to push to branches. Ping me if you’re having problems.
 
Please update the translations board as you work on the translation: https://github.com/nextstrain/translations/projects/1
 
Please assign yourself to the translation if you’re working on it this week.
 
When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it! 
 
Use the [discussion board for your team](https://github.com/orgs/nextstrain/teams/mandarin). Discussion boards are a place for you to communicate together, and unlike issues, they won’t disappear. It’s a good place to sort out translation workflows, post a dictionary for technical terms, whatever you need as a team.
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Mandarin-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Mandarin; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in the field. Although if you have more, that’s fine too.
 
Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.  
 
**Thank you so very much! It’s an honor to fight the pandemic with you. I continue to hope you and your loved ones are well.**

**Comment by lxy0107** [comment]
Hi all, I'll start, anyone who wants to work on it now can start from page 9.

**Comment by lxy0107** [comment]
Hi all, I will precede from text 9 now

**Comment by fzhang12** [comment]
Thanks @lxy0107 . Have you done with your translation? I have some time now to work on it. Should I start from the beginning?

**Comment by lxy0107** [comment]
@fzhang12 Just 10 more min for me for the last check... thanks!!!

**Comment by lxy0107** [comment]
@fzhang12 I'm done, please proofread:)

**Comment by fzhang12** [comment]
@lxy0107 great job! I have finished my comments. 
I probably edited quite some to add fluency. Could you take another look? 
Any comment is welcome.

**Comment by lxy0107** [comment]
@fzhang12 thanks for editing! I made a few small changes, if you agree, you can change the status to ’Ready for publication'.

**Comment by fzhang12** [comment]
@lxy0107 Thanks for the review. I will now change the status and pull a request for publication.

**Comment by cassiawag** [comment]
Amazing work @fzhang12 & @lxy0107! That was very fast :)

Can one of you translate this tweet for me? After last week's fiasco, I want to do better:

"The latest #COVID19 #SARSCov2 situaton report is now available in Chinese. Thank you @3Xueying and @fengjun_zhang for the rapid translation.

This week we cover the latest data from Japan, Senegal, Democratic Republic of the Congo, Iceland, Austria, Canada, and the USA."

**Comment by fzhang12** [comment]
@cassiawag followed up this time 😂

"最新的 #新冠病毒 #COVID19 #SARSCov2 状况中文版已经上线 。非常感谢 @3Xueying 和 @fengjun_zhang 对这周报告的及时高效翻译。

这周我们将分析日本，塞内加尔，刚果民主共和国，冰岛，奥地利，加拿大和美国的疫情最新进展。"

**Comment by fzhang12** [comment]
@cassiawag moment I missed 2 characters...

"最新的 #新冠病毒 #COVID19 #SARSCov2 状况报告中文版已经上线 。非常感谢 @3Xueying 和 @fengjun_zhang 对这周报告的及时高效翻译。

这周我们将分析日本，塞内加尔，刚果民主共和国，冰岛，奥地利，加拿大和美国的疫情最新进展。"

**Comment by cassiawag** [comment]
Thanks @fzhang12!

It's published here: https://nextstrain.org/narratives/ncov/sit-rep/zh/2020-04-03.

Please share around with colleagues. You should also know that your translations are definitely being read! Over the last month, Chinese sit-reps have had ~37k unique views, according to Google Analytics. The actual number is likely higher because people often block Google Analytics.
