### ISSUE TITLE
Translate "How to interpret phylogenetic trees" into Indonesian

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#138]
Hi @kumincir & @sentausa,

I've really appreciated your efficiency and hard work on situation reports week after week. I'd really love to translate [How to interpret phylogenetic trees](https://nextstrain.org/narratives/trees-background) into Indonesian as I think this could help make these reports even more accessible. 

I've created a branch `trees_id` to translate this on. The file to translate is here: https://github.com/nextstrain/translations/blob/trees_id/narratives/translations_trees-background_id.md

The link to preview is here: https://nextstrain.org/community/narratives/nextstrain/translations@trees_id/trees-background/id

Extra care should be taken with this translation as it's quite technical and will be referenced in every future report.

Thanks so much!
Cassia

**Comment by sentausa** [comment]
Hi @cassiawag,
It's a really great and timely idea, as there are now 3 sequences from Indonesia on Nextstrain, and people (at least the scientists, and one non-scientist who tagged both @kumincir & me on Facebook) there started to check them out. So yeah, I think it'll be great if we translate it.

**Comment by sentausa** [comment]
@cassiawag I just saw a typo in the original text. In slide 4 (How does the "diversity" panel relate to the tree?), second paragraph, last sentence, the word "intimitely" should be "intimately".

**Comment by cassiawag** [comment]
Thanks @sentausa; I'll get that typo fixed. Glad to hear you're on the translation!

**Comment by sentausa** [comment]
Finished translating, waiting for @kumincir for review

**Comment by kumincir** [comment]
Ready for publication :)

**Comment by cassiawag** [comment]
Thanks so much @sentausa & @kumincir! I've published it here: https://nextstrain.org/narratives/trees-background/id

I was also excited to see the Indonesian sequences on Nextstrain.
