### ISSUE TITLE
Translate April 3 COVID-19 report into Portuguese

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#14]
Hello @EricaBarroso @7glaucio @andersonbrito !
 
The situation report from 2020-04-03  is ready to be translated to Portuguese. 
Branch to translate on: `sit-rep_pt` 
File to translate: https://github.com/nextstrain/translations/blob/sit-rep_pt/narratives/translations_ncov_sit-rep_pt_2020-04-03.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!
Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_pt/ncov/sit-rep/pt/2020-04-03
 
**Logistics**
Once you’ve accepted my invitation to join the Nextstrain organization and the `translations` repo, you should have access to push to branches. Ping me if you’re having problems.
 
Please update the translations board as you work on the translation: https://github.com/nextstrain/translations/projects/1
 
Please assign yourself to the translation if you’re working on it this week.
 
When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it! 
 
Use the [discussion board for your team](https://github.com/orgs/nextstrain/teams/portuguese). Discussion boards are a place for you to communicate together, and unlike issues, they won’t disappear. It’s a good place to sort out translation workflows, post a dictionary for technical terms, whatever you need as a team.
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Portuguese-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Portuguese; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in the field. Although if you have more, that’s fine too.
 
Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.  
 
**Thank you so very much! It’s an honor to fight the pandemic with you. I continue to hope you and your loved ones are well.**

**Comment by 7glaucio** [comment]
Alright. As usual if nobody starts earlier, I will take a look tonight.

**Comment by EricaBarroso** [comment]
Hi Anderson, we made a WhatsApp group..

**Comment by 7glaucio** [comment]
It's done, guys. Please feel free to proofread and have it published once is ready. @EricaBarroso @andersonbrito Just a heads up: I noticed you guys started using "cluster", so I did as well this time. I didn't know it was a recurring word even on portuguese scientific-speaking so far.

**Comment by EricaBarroso** [comment]
I just made a few suggestions.

Best,
Erica.

**Comment by cassiawag** [comment]
@EricaBarroso -- After your suggestions, do you think it's good to publish?

**Comment by EricaBarroso** [comment]
Hi Cassia, I would say so!

**Comment by EricaBarroso** [comment]
*just made some more sugestions

**Comment by cassiawag** [comment]
Thanks Erica! Although I'm not seeing where you made the suggestions. It looks like the last commit is from a few days ago from @7glaucio.

**Comment by EricaBarroso** [comment]
Luckily I saved the changes in another place. Will try to send it to you
again, sorry!

**Comment by cassiawag** [comment]
@EricaBarroso -- it looks like you need to accept my invitation to join the Nextstrain organization and translator teams. Let me know if you have trouble doing so.

**Comment by EricaBarroso** [comment]
I have not saved the changes, so I had to do it again (at least I
remembered what I have done).

Sent a pull request now. Hope now it works!!

**Comment by cassiawag** [comment]
I've merged in your pull request, so it can be previewed here: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_pt/ncov/sit-rep/pt/2020-04-03.

Does that look correct @EricaBarroso? @7glaucio, are you agreed that it's good to publish?

**Comment by 7glaucio** [comment]
Yeah @cassiawag, it seems alright.

**Comment by EricaBarroso** [comment]
Yes. Thanks!

**Comment by cassiawag** [comment]
Great, I'm going to get this published. @EricaBarroso, do you have a twitter handle you'd like me to tag?

**Comment by cassiawag** [comment]
It's live here: https://nextstrain.org/narratives/ncov/sit-rep/pt/2020-04-03

Thanks so much @7glaucio & @EricaBarroso!! Hope you have good rest of your weeks, all things considered.

**Comment by EricaBarroso** [comment]
shared in my social media (I don't use much twitter). Thanks :)
