### ISSUE TITLE
Translate April 3 COVID-19 report into Russian

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#15]
Hello @dtaliun @frogtraveler @vpuller @irina95511 !
 
The situation report from 2020-04-03  is ready to be translated to Russian. 
Branch to translate on: `sit-rep_ru` 
File to translate: https://github.com/nextstrain/translations/blob/sit-rep_ru/narratives/translations_ncov_sit-rep_ru_2020-04-03.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!
Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_ru/ncov/sit-rep/ru/2020-04-03
 
**Logistics**
Once you’ve accepted my invitation to join the Nextstrain organization and the `translations` repo, you should have access to push to branches. Ping me if you’re having problems.
 
Please update the translations board as you work on the translation: https://github.com/nextstrain/translations/projects/1
 
Please assign yourself to the translation if you’re working on it this week.
 
When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it! 
 
Use the [discussion board for your team](https://github.com/orgs/nextstrain/teams/russian). Discussion boards are a place for you to communicate together, and unlike issues, they won’t disappear. It’s a good place to sort out translation workflows, post a dictionary for technical terms, whatever you need as a team.
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Russian-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Russian; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in the field. Although if you have more, that’s fine too.
 
Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.  
 
**Thank you so very much! It’s an honor to fight the pandemic with you. I continue to hope you and your loved ones are well.**

**Comment by dtaliun** [comment]
Working on "Table of Contents" and "Resources" sections

**Comment by cassiawag** [comment]
And it's live here: https://nextstrain.org/narratives/ncov/sit-rep/ru/2020-04-03 !

Thanks so much @irina95511 & @dtaliun. Have a good weekend.
