### ISSUE TITLE
Translate August 14 sit-rep into Indonesian

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#219]
Greetings @nextstrain/indonesian,

It’s really great to work with you again after a long situation report hiatus.

Our August update on genomic epidemiology of COVID-19 is ready to be translated to Indonesian. This is just a one-off situation report, and we are not planning to resume weekly situation reports at this time. Translation of this report is less time sensitive than previous ones, so feel free to take a bit longer on the translation. I won’t be available for much of the weekend, so may not be able to publish it until Sunday anyway.

Branch to translate on: `sit-rep_id`

File to translate: https://github.com/nextstrain/translations/blob/sit-rep_id/narratives/translations_ncov_sit-rep_id_2020-08-14.md. You can translate directly in this file, but please remember to push often.

Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_id/ncov/sit-rep/id/2020-08-14

Please translate the Twitter post below too :)

Thank you so much! Sending warm, safe thoughts to you and your loved ones and hoping for wisdom in our respective leaders.

Take care,
Cassia

**Twitter post**
Check out our August report on COVID-19 genomic epidemiology in Indonesian. In it, we explore the global spread of the virus broadly and provide specific updates for each world region.
Thank you to @, @, and @ for their rapid translation!

**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7

Please assign yourself to the translation if you’re working on it this week.

When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it!

Discussion board for your team is here: https://github.com/orgs/nextstrain/teams/indonesian

**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. Feel free to update internal links to refer to the Indonesian version of the narrative(s). I can also update those when I publish it though.

Please keep the number of and text for Table of Contents links the same in your translation as in the English narrative.

Please add your name under `translators:` with new line, tab, and dash, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.

Note: You may know of other great resources available in Indonesian; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy.

At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.

**Comment by kumincir** [comment]
Twitter post
Kunjungi laporan Agustus kami mengenai epidemiologi genomik COVID-19 dalam bahasa Indonesia. Di dalamnya, kami menjelajahi penyebaran global si virus secara luas dan menyediakan pemutakhiran spesifik untuk setiap wilayah dunia.
Terima kasih @sentausa dan @wikidisastra atas terjemahan cepatnya!

@sentausa mohon koreksinya

**Comment by cassiawag** [comment]
Hello @kumincir & @sentausa, just wanted to check in on how the translation is coming? Ideally, we'd like to publish something soon. Thank you so much for your hardwork on it!

**Comment by kumincir** [comment]
Waiting for 2nd person's proofread/review @sentausa

**Comment by sentausa** [comment]
It's reviewed @cassiawag. Thanks @kumincir for doing the translation.

Twitter post
Lihatlah laporan edisi Agustus dari kami mengenai epidemiologi genomik COVID-19 dalam bahasa Indonesia. Di dalamnya, kami mengeksplorasi penyebaran global virus ini secara umum dan menyediakan pemutakhiran spesifik untuk setiap wilayah dunia.
Terima kasih @sentausa dan @wikidisastra atas terjemahan cepatnya!

**Comment by cassiawag** [comment]
Published and tweeted: https://nextstrain.org/narratives/ncov/sit-rep/id/2020-08-14

Thank you so much both -- sorrry for the delay on publication.
