### ISSUE TITLE
Translate August 14 sit-rep into Italian

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#220]
Greetings @nextstrain/italian,

It’s really great to work with you again after a long situation report hiatus.

Our August update on genomic epidemiology of COVID-19 is ready to be translated to Italian. This is just a one-off situation report, and we are not planning to resume weekly situation reports at this time. Translation of this report is less time sensitive than previous ones, so feel free to take a bit longer on the translation. I won’t be available for much of the weekend, so may not be able to publish it until Sunday anyway.

Branch to translate on: `sit-rep_it`

File to translate: https://github.com/nextstrain/translations/blob/sit-rep_it/narratives/translations_ncov_sit-rep_it_2020-08-14.md. You can translate directly in this file, but please remember to push often.

Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_it/ncov/sit-rep/it/2020-08-14

Please translate the Twitter post below too :)

Thank you so much! Sending warm, safe thoughts to you and your loved ones and hoping for wisdom in our respective leaders.

Take care,
Cassia

**Twitter post**
Check out our August report on COVID-19 genomic epidemiology in Italian. In it, we explore the global spread of the virus broadly and provide specific updates for each world region.
Thank you to @, @, and @ for their rapid translation!

**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7

Please assign yourself to the translation if you’re working on it this week.

When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it!

Discussion board for your team is here: https://github.com/orgs/nextstrain/teams/italian

**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. Feel free to update internal links to refer to the Italian version of the narrative(s). I can also update those when I publish it though.

Please keep the number of and text for Table of Contents links the same in your translation as in the English narrative.

Please add your name under `translators:` with new line, tab, and dash, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.

Note: You may know of other great resources available in Italian; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy.

At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.

**Comment by cassiawag** [comment]
Hello all-star Italian team! I keep seeing the notifications on your chat :) Just checking in on how the translation is going? Ideally, I'd like to publish it soon.

@nextstrain/italian

**Comment by aliceLedda** [comment]
Hello Cassia,
unfortunately we are going slowly. Partly due to (lack of) access to
internet connection and being busy, partly last weekend was a kind of
Christmas in summer in Italy, so it was difficult to be working through it.
How much time do you give us? Maybe we could be done in the weekend.
Best wishes,
Alice

**Comment by cassiawag** [comment]
Hi Alice,
I do understand! Celebrations are important, and I won't be around this weekend either. Aiming to be done by next Monday would be ideal.
Regards,
Cassia

**Comment by aliceLedda** [comment]
Ok then! Let's have it done by Monday!
Enjoy your celebrations!
Alice

**Comment by aliceLedda** [comment]
Dear Cassia,
I think it's done... Alessia and Sara do you confirm?
Thanks for your patience!
Alice

**Comment by al-epo** [comment]
yes, I confirm ! :-)

**Comment by cassiawag** [comment]
Woohoo!! I'm going to go ahead and publish

**Comment by cassiawag** [comment]
It's published: https://nextstrain.org/narratives/ncov/sit-rep/it/2020-08-14

@aliceLedda @sarameiqi @al-epo -- would anyone like to translate the Twitter post?

**Comment by aliceLedda** [comment]
*Twitter post*
Check out our August report on COVID-19 genomic epidemiology in Italian. In
it, we explore the global spread of the virus broadly and provide specific
updates for each world region.
Thank you to @, @, and @ for their rapid translation!

Ecco a voi il report di agosto sull'epidemiologia genetica di COVID-19
tradotto in Italiano!
Esaminiamo la diffusione globale del virus e forniamo aggiornamenti
specifici su ciascuna regione del mondo.
Ringraziamo @aliceLedda <https://github.com/aliceLedda> @sarameiqi
<https://github.com/sarameiqi> @al-epo <https://github.com/al-epo> per la
loro rapida traduzione!

Sorry Cassia for the late translation and thanks for all your efforts!
Looking forward for the next translation!
Alice

**Comment by cassiawag** [comment]
Thank you Alice! I've tweeted it :)

**Comment by aliceLedda** [comment]
Thank you Cassia!
:)
