### ISSUE TITLE
Translate August 14 sit-rep into Japanese

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#221]
Greetings @nextstrain/japanese,

It’s really great to work with you again after a long situation report hiatus.

Our August update on genomic epidemiology of COVID-19 is ready to be translated to Japanese. This is just a one-off situation report, and we are not planning to resume weekly situation reports at this time. Translation of this report is less time sensitive than previous ones, so feel free to take a bit longer on the translation. I won’t be available for much of the weekend, so may not be able to publish it until Sunday anyway.

Branch to translate on: `sit-rep_ja`

File to translate: https://github.com/nextstrain/translations/blob/sit-rep_ja/narratives/translations_ncov_sit-rep_ja_2020-08-14.md. You can translate directly in this file, but please remember to push often.

Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_ja/ncov/sit-rep/ja/2020-08-14

Please translate the Twitter post below too :)

Thank you so much! Sending warm, safe thoughts to you and your loved ones and hoping for wisdom in our respective leaders.

Take care,
Cassia

**Twitter post**
Check out our August report on COVID-19 genomic epidemiology in Japanese. In it, we explore the global spread of the virus broadly and provide specific updates for each world region.
Thank you to @, @, and @ for their rapid translation!

**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7

Please assign yourself to the translation if you’re working on it this week.

When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it!

Discussion board for your team is here: https://github.com/orgs/nextstrain/teams/japanese

**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. Feel free to update internal links to refer to the Japanese version of the narrative(s). I can also update those when I publish it though.

Please keep the number of and text for Table of Contents links the same in your translation as in the English narrative.

Please add your name under `translators:` with new line, tab, and dash, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.

Note: You may know of other great resources available in Japanese; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy.

At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.

**Comment by tomoyuki-nezu** [comment]
Long time no see Cassia, and How is everyone?
Japan isn't the worst, but I think the Japanese government can do a little more...

I read the report interestingly. I have some time on the weekend, but I don't know how much I can translate during the weekend because this report was bit large text. If anyone can translate, please translate from the European section.

**Comment by cassiawag** [comment]
No worries @tomoyuki-nezu. I know it's long! I'm doing well. How are you?

**Comment by cassiawag** [comment]
@satotake, @tomoyuki-nezu, @fzhang12 -- hello all! I just wanted to check in on how the Japanese translation is coming along.  Japanese does continue to be one of Nextstrain's top languages and the Japanese sit-reps from May and earlier are still read quite regularly. I'd love to give those readers an update!

Of course, if you're not available, that's very understandable. Just let me know, and I'd ideally like to publish something soon.

**Comment by fzhang12** [comment]
Thanks for the reminder @cassiawag . I am willing to help the Japanese translation. But I am afraid it wont be easy for me to translate major parts since it is not my native language actually. We will see if I can help much during the weekend.

**Comment by tomoyuki-nezu** [comment]
@cassiawag I didn't get the time this week. I reserve time on weekends. Please wait a little bit...

**Comment by fzhang12** [comment]
I started from Europe part as @tomoyuki-nezu suggested yesterday. I will continue work on it today.

**Comment by satotake** [comment]
Hi folks, I will in this weekend...but may be late

@fzhang12 has almost done from Europe section to the end.
And @tomoyuki-nezu will translate from start to Europe section in this weekend.

If anything for me is left, I will do in this weekend (maybe review?)

**Comment by fzhang12** [comment]
Just finished the second part of the translation (from Europe to scientific credit)
I will now hand over the rest to you two :)
And nice weekend~~

**Comment by tomoyuki-nezu** [comment]
Translated the first half. The original text is now fully translated.
I may adjust the overall tone after this, but it's okay for you to review it > @fzhang12 

I apologize for the delay in work.
During the past week, I couldn't get the time due to summer vacation and other work.
I am living my daily life while devising various new-things :)

**Comment by tomoyuki-nezu** [comment]
Translated the first half. The original text is now fully translated.
I may adjust the overall tone after this, but it's okay for you to review it > @fzhang12 @satotake 

I apologize for the delay in work.
During the past week, I couldn't get the time due to summer vacation and other work.
I am living my daily life while devising various new-things :)

**Comment by satotake** [comment]
I have just reviewed. Thank you for your hard work. @tomoyuki-nezu @fzhang12 
Please check my changes.

**Comment by fzhang12** [comment]
I went through really quick at the changes of @satotake and the other part of the content from @tomoyuki-nezu 
I think it all good and for me fluent enough
So i would suggest it ready for publication.

Thanks both and happy working with you

**Comment by cassiawag** [comment]
Thank you @fzhang12, @satotake & @tomoyuki-nezu :)

It's published and tweeted: https://nextstrain.org/narratives/ncov/sit-rep/ja/2020-08-14
