### ISSUE TITLE
Translate August 15 sit-rep into Mandarin Chinese

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#223]
Greetings @nextstrain/mandarin,

It’s really great to work with you again after a long situation report hiatus.

Our August update on genomic epidemiology of COVID-19 is ready to be translated to Mandarin. This is just a one-off situation report, and we are not planning to resume weekly situation reports at this time. Translation of this report is less time sensitive than previous ones, so feel free to take a bit longer on the translation. I won’t be available for much of the weekend, so may not be able to publish it until Sunday anyway.

Branch to translate on: `sit-rep_zh`

File to translate: https://github.com/nextstrain/translations/blob/sit-rep_zh/narratives/translations_ncov_sit-rep_zh_2020-08-14.md. You can translate directly in this file, but please remember to push often.

Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_zh/ncov/sit-rep/zh/2020-08-14

Please translate the Twitter post below too :)

Thank you so much! Sending warm, safe thoughts to you and your loved ones and hoping for wisdom in our respective leaders.

Take care,
Cassia

**Twitter post**
Check out our August report on COVID-19 genomic epidemiology in Mandarin. In it, we explore the global spread of the virus broadly and provide specific updates for each world region.
Thank you to @, @, and @ for their rapid translation!

**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7

Please assign yourself to the translation if you’re working on it this week.

When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it!

Discussion board for your team is here: https://github.com/orgs/nextstrain/teams/mandarin

**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. Feel free to update internal links to refer to the Mandarin version of the narrative(s). I can also update those when I publish it though.

Please keep the number of and text for Table of Contents links the same in your translation as in the English narrative.

Please add your name under `translators:` with new line, tab, and dash, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.

Note: You may know of other great resources available in Mandarin; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy.

At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.

**Comment by cassiawag** [comment]
Hello @fillorkill, @alvinxhan, @lxy0107, @fzhang12, just wanted to check-in and see how things are going with the translation? If you are able to work on it, I'd love to get something published soon! Chinese continues to be one of our most popular languages, and the Chinese sit-rep from May still gets read quite regularly.

Of course, if you're not available, I do understand, and I can close this issue. Just let me know. Cheers!

**Comment by lxy0107** [comment]
Hi all, I can try to finish the translation tonight if someone is up for proofreading it!

**Comment by fzhang12** [comment]
Thanks @lxy0107 then I will work on the proofread tomorrow.

**Comment by cassiawag** [comment]
Woohoo! Thanks so much!

**Comment by fzhang12** [comment]
@lxy0107 morning, have you finished the first draft yet? Should I move onto proofreading?

**Comment by lxy0107** [comment]
Not yet 😂 I will finish it today if that’s ok...

**Comment by fzhang12** [comment]
> Not yet 😂 I will finish it today if that’s ok...
> […](#)
> Sent from my iPhone
> On 21. Aug 2020, at 09:09, fzhang12 ***@***.***> wrote: ﻿ @lxy0107 morning, have you finished the first draft yet? Should I move onto proofreading? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

No worries. I'm just asking. Take your time:)

**Comment by lxy0107** [comment]
It's ready for proofreading:)

**Comment by cassiawag** [comment]
Thanks @lxy0107! @fzhang12, any chance you'll be able to take a look!

**Comment by fzhang12** [comment]
I reviewed @lxy0107 work and it was great as usually.

Twitter post
请翻阅我们对于新冠肺炎最新的八月报告中文版。这一期，我们探索了新冠病毒在全世界范围内的传播，针对每一个地区更新了一些内容。
非常感谢 @3Xueying 和 @fengjun_zhang 的翻译！

Sorry that I had to remove the word "fast" in twitter post 
And my apologies to the late respond @cassiawag

**Comment by cassiawag** [comment]
Thank you at @lxy0107 & @fzhang12!

It's published and tweeted: https://nextstrain.org/narratives/ncov/sit-rep/zh/2020-08-14
