### ISSUE TITLE
Translate August 14 sit-rep into Polish

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#224]
Greetings @nextstrain/polish,

It’s really great to work with you again after a long situation report hiatus.

Our August update on genomic epidemiology of COVID-19 is ready to be translated to Polish. This is just a one-off situation report, and we are not planning to resume weekly situation reports at this time. Translation of this report is less time sensitive than previous ones, so feel free to take a bit longer on the translation. I won’t be available for much of the weekend, so may not be able to publish it until Sunday anyway.

Branch to translate on: `sit-rep_pl`

File to translate: https://github.com/nextstrain/translations/blob/sit-rep_pl/narratives/translations_ncov_sit-rep_pl_2020-08-14.md. You can translate directly in this file, but please remember to push often.

Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_pl/ncov/sit-rep/pl/2020-08-14

Please translate the Twitter post below too :)

Thank you so much! Sending warm, safe thoughts to you and your loved ones and hoping for wisdom in our respective leaders.

Take care,
Cassia

**Twitter post**
Check out our August report on COVID-19 genomic epidemiology in Polish. In it, we explore the global spread of the virus broadly and provide specific updates for each world region.
Thank you to @, @, and @ for their rapid translation!

**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7

Please assign yourself to the translation if you’re working on it this week.

When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it!

Discussion board for your team is here: https://github.com/orgs/nextstrain/teams/polish

**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. Feel free to update internal links to refer to the Polish version of the narrative(s). I can also update those when I publish it though.

Please keep the number of and text for Table of Contents links the same in your translation as in the English narrative.

Please add your name under `translators:` with new line, tab, and dash, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.

Note: You may know of other great resources available in Polish; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy.

At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.

**Comment by aniafijarczyk** [comment]
proofreading done, thanks again @M-nied7 for translating all text!

twitter post:
Sprawdź nasz sierpniowy raport dotyczący epidemiologii genomowej COVID-19 w języku polskim. Badamy w nim globalne rozprzestrzenianie się wirusa i opisujemy aktualizacje dla każdego regionu świata.
Dziękuję @pandkaruda i @afijarczyk za szybkie tłumaczenie!

**Comment by cassiawag** [comment]
Published and tweeted: https://nextstrain.org/narratives/ncov/sit-rep/pl/2020-08-14

Thanks so much Marta and Anna!
