### ISSUE TITLE
Translate August 14 sit-rep into Portuguese

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#225]
Greetings @nextstrain/portuguese,

It’s really great to work with you again after a long situation report hiatus.

Our August update on genomic epidemiology of COVID-19 is ready to be translated to Portuguese. This is just a one-off situation report, and we are not planning to resume weekly situation reports at this time. Translation of this report is less time sensitive than previous ones, so feel free to take a bit longer on the translation. I won’t be available for much of the weekend, so may not be able to publish it until Sunday anyway.

Branch to translate on: `sit-rep_pt`

File to translate: https://github.com/nextstrain/translations/blob/sit-rep_pt/narratives/translations_ncov_sit-rep_pt_2020-08-14.md. You can translate directly in this file, but please remember to push often.

Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_pt/ncov/sit-rep/pt/2020-08-14

Please translate the Twitter post below too :)

Thank you so much! Sending warm, safe thoughts to you and your loved ones and hoping for wisdom in our respective leaders.

Take care,
Cassia

**Twitter post**
Check out our August report on COVID-19 genomic epidemiology in Portuguese. In it, we explore the global spread of the virus broadly and provide specific updates for each world region.
Thank you to @, @, and @ for their rapid translation!

**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7

Please assign yourself to the translation if you’re working on it this week.

When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it!

Discussion board for your team is here: https://github.com/orgs/nextstrain/teams/portuguese

**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. Feel free to update internal links to refer to the Portuguese version of the narrative(s). I can also update those when I publish it though.

Please keep the number of and text for Table of Contents links the same in your translation as in the English narrative.

Please add your name under `translators:` with new line, tab, and dash, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.

Note: You may know of other great resources available in Portuguese; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy.

At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.

**Comment by amadotalita** [comment]
Ok Cassia, I got this one ;)

**Comment by amadotalita** [comment]
Hello people! The translation is ready for review. Here is the twitter post:

Confira nosso relatório de agosto sobre epidemiologia genômica do COVID-19 em português. Nele, exploramos a propagação global do vírus de forma ampla e fornecemos atualizações específicas para cada região do mundo.
Obrigado a  @amadotalita , @, and @ pela rápida tradução!

**Comment by andersonbrito** [comment]
Thank you, Talita.
I'll read and review it now.

Cheers,

*Anderson Brito*

**Comment by andersonbrito** [comment]
Hi,

I reviewed up to the 'South America' section, but the remaining pages are
still in English.
I've extended the translation further, to finish the South America section,
but stopped to check if maybe Talita has that part already translated (but
not uploaded yet).

Talita, do you happen to have the rest of the text in your computer?
If not, let me know if you want help finishing that part: I can move on
with the translation this morning/afternoon.

Best,



*Anderson Brito*

**Comment by amadotalita** [comment]
Ok, I just send the rest of the translation. Sorry about that! 

Cheers,

T.

**Comment by andersonbrito** [comment]
Done! Thank you, Talita.

Cassia, it is now ready for posting.

Best,

*Anderson Brito*

**Comment by cassiawag** [comment]
Published and tweeted: https://nextstrain.org/narratives/ncov/sit-rep/pt/2020-08-14

Thanks for the hard work Talita and Anderson!
