### ISSUE TITLE
Translate August 14 sit-rep into Russian

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#226]
Greetings @nextstrain/russian,

It’s really great to work with you again after a long situation report hiatus.

Our August update on genomic epidemiology of COVID-19 is ready to be translated to Russian. This is just a one-off situation report, and we are not planning to resume weekly situation reports at this time. Translation of this report is less time sensitive than previous ones, so feel free to take a bit longer on the translation. I won’t be available for much of the weekend, so may not be able to publish it until Sunday anyway.

Branch to translate on: `sit-rep_ru`

File to translate: https://github.com/nextstrain/translations/blob/sit-rep_ru/narratives/translations_ncov_sit-rep_ru_2020-08-14.md. You can translate directly in this file, but please remember to push often.

Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_ru/ncov/sit-rep/ru/2020-08-14

Please translate the Twitter post below too :)

Thank you so much! Sending warm, safe thoughts to you and your loved ones and hoping for wisdom in our respective leaders.

Take care,
Cassia

**Twitter post**
Check out our August report on COVID-19 genomic epidemiology in Russian. In it, we explore the global spread of the virus broadly and provide specific updates for each world region.
Thank you to @, @, and @ for their rapid translation!

**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7

Please assign yourself to the translation if you’re working on it this week.

When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it!

Discussion board for your team is here: https://github.com/orgs/nextstrain/teams/russian

**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. Feel free to update internal links to refer to the Russian version of the narrative(s). I can also update those when I publish it though.

Please keep the number of and text for Table of Contents links the same in your translation as in the English narrative.

Please add your name under `translators:` with new line, tab, and dash, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.

Note: You may know of other great resources available in Russian; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy.

At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.

**Comment by frogtraveler** [comment]
Hi Cassia! Nice to see an update! I'll start translating.

**Comment by frogtraveler** [comment]
@cassiawag Do you know if in the summary, in the sentence: "As the pandemic reaches its eighth month of global circulation, we can now see distinct changes over time in the picture painted by viral genetics, largely determined by changing behaviour." Under "behaviour" we are talking about human behavior?

Also, is word "restrictions" missing from this sentence: "In the USA, the absence of strict domestic travel "" has helped maintain well-mixed epidemics between states."?

**Comment by frogtraveler** [comment]
Here is the twitter post translation:
А вот и наш августовский отчет о геномной эпидемиологии COVID-19 на русском языке. В нем мы исследуем в общих чертах глобальное распространение вируса и предоставляем специальные обновления для каждого региона.
Спасибо @varvarakozyreva и @MEKlab за быстрый перевод!

**Comment by irina95511** [comment]
Hi @cassiawag , we have finished and proofread the translation! Thanks for the report, it is good hearing news from you and it was a pleasure to help. Please, take care too.

**Comment by cassiawag** [comment]
@frogtraveler -- restrictions is definitely missing from that sentence. I'll take a look at the English version and check if it's correct. And behavior is referring to human behavior. Sorry for the delay in getting back to you! I was camping all weekend and didn't have access to internet.

Thank you both for the translation. I'll get it published.

**Comment by cassiawag** [comment]
Tweeted and published: https://nextstrain.org/narratives/ncov/sit-rep/ru/2020-08-14

Good to hear from you both again!

**Comment by frogtraveler** [comment]
@cassiawag Happy to help! 
Camping is the best time spending right now. I went to Yellowstone just recently myself :) Stay safe! 
Looking forward to any future updates from Nextstrain, whenever those might be!

**Comment by cassiawag** [comment]
I love Yellowstone. In college, I studied archaeal viruses from the hot springs there; glad you were able to make a trip out! I'll let you know about updates.
