### ISSUE TITLE
Translate August 14 sit-rep into Bengali, Czech, Filipino, Hindi, Swahili, Urdu, & Vietnamese

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#229]
Hi @VengaLing,

The May August 14 situation report is ready to be translated. Thank you so much for being able to do this on such short notice! See below for branches and file names. Feel free to just grab the file from one branch and rename it; they are all the same.

When the translations are completed, please merge them back into the appropriate branch. This will allow me to preview it to confirm the formatting is a-ok before pushing it to the master branch.

As I said in the email, turn around time does not matter so much for this narrative. Thanks again!
Cassia

Bengali
branch: `sit-rep_bn`
file: https://github.com/nextstrain/translations/blob/sit-rep_bn/narratives/translations_ncov_sit-rep_bn_2020-08-14.md

Czech
branch: `sit-rep_cs`
file: https://github.com/nextstrain/translations/blob/sit-rep_cs/narratives/translations_ncov_sit-rep_cs_2020-08-14.md

Filipino
branch: `sit-rep_tl`
file: https://github.com/nextstrain/translations/blob/sit-rep_tl/narratives/translations_ncov_sit-rep_tl_2020-08-14.md

Hindi
branch: `sit-rep_hi`
file: https://github.com/nextstrain/translations/blob/sit-rep_hi/narratives/translations_ncov_sit-rep_hi_2020-08-14.md

Swahili
branch: `sit-rep_sw`
file: https://github.com/nextstrain/translations/blob/sit-rep_sw/narratives/translations_ncov_sit-rep_sw_2020-08-14.md

Urdu
branch: `sit-rep_ur`
file: https://github.com/nextstrain/translations/blob/sit-rep_ur/narratives/translations_ncov_sit-rep_ur_2020-08-14.md

Vietnamese
branch: `sit-rep_vi`
file: https://github.com/nextstrain/translations/blob/sit-rep_vi/narratives/translations_ncov_sit-rep_vi_2020-08-14.md

**Comment by cassiawag** [comment]
Swahili, Czech, and Hindi translations are out!

**Comment by VengaLing** [comment]
All language uploaded

<https://www.vengaglobal.com/>

Chris Phillips
Chief Operations Officer

Your Go Global Partner
www.vengaglobal.com

<https://www.linkedin.com/company/venga-localization/>
<https://www.facebook.com/VengaGlobal/>  <https://twitter.com/VengaGlobal>
MOBILE:  +44 (0) 7740024215
Suite 408, 154 - 160 Fleet Street
London EC4A 2DQ, UK
E-MAIL:  chris.phillips@vengaglobal.com

**Comment by cassiawag** [comment]
Awesome thanks! I'll get these uploaded.

**Comment by cassiawag** [comment]
All are published; thanks again, Chris!
