### ISSUE TITLE
Translate April 10 report into Turkish

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#28]
Hello @nextstrain/turkish!
 
The situation report from 2020-04-10  is ready to be translated to Turkish. This week’s report is a little bit shorter than usual but hopefully still informative :)
 
Branch to translate on: `sit-rep_tr` 
 
File to translate: https://github.com/nextstrain/translations/blob/sit-rep_tr/narratives/translations_ncov_sit-rep_tr_2020-04-10.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_tr/ncov/sit-rep/tr/2020-04-10
 
Can someone please translate this Twitter post? The other option is me using Google Translate, which is probably not a good idea:
“This week’s situation report traces how the #COVID19 outbreak unfolded, month by month. It’s now available in Turkish: https://nextstrain.org/narratives/ncov/sit-rep/tr/2020-04-10. 
 
Thank you @, @, and @ for the rapid translation!” 
 
**Logistics**
Please update the translations board as you work on the translation: 
https://github.com/orgs/nextstrain/projects/7
 
Please assign yourself to the translation if you’re working on it this week.
 
When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it! 
 
Feel free to use the [discussion board for your team](https://github.com/orgs/nextstrain/teams/turkish). Discussion boards are team specific, and unlike issues, they won’t disappear. It’s a good place to sort out translation workflows, post a dictionary for technical terms, etc.
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
Note: You may know of other great resources available in Turkish; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.
 
Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.  
 
**Thank you so very much all! Ya’ll are an incredible team to work with.**

**Comment by zeynephrc** [comment]
Hello!

@erenada  could you please move the file to hackmd if it is okay for everyone? i'm not really familiar with hackmd's interface so it would be really nice if you can help with that. 

and also, it would be great to share the sections and work like that to finish it rapidly!

thanks in advance everyone!

**Comment by benuraa** [comment]
Hello! I have a prior commitment for tomorrow morning and have time now, so I will translate from "Subsequent spread across international borders within regions." to the end. I am happy to proofread in the afternoon (pm in EST)  tomorrow if needed. Stay safe!

**Comment by zeynephrc** [comment]
Okay then, I will be translating the "Early spread within Asia" and "Initial introductions to other regions"

**Comment by erenada** [comment]
Hi @zeynephrc @benuraa,

Sorry I am late! I've moved the page to HackMd, we can continue there! 

Here is the hackmd link: https://hackmd.io/@nextstrainTurkish/S1eutrJuL/edit

**Comment by erenada** [comment]
I think it is done guys, well done! @benuraa you can now proof-read; let us know if something has to change. Thank you!

**Comment by benuraa** [comment]
@zeynephrc @erenada Great job guys! I changed a couple of words here and there. @cassiawag it is ready to go! 

"Bu haftaki raporda #COVID19 salgının nasıl ilerlediğini analiz ettik. Raporun Türkçe için: https://nextstrain.org/narratives/ncov/sit-rep/tr/2020-04-10. @zharcanoglu , @erenada  ve @benuraaa 'ya hızlı çevirileri için teşekkürler."

**Comment by benuraa** [comment]
btw @cassiawag there is a title with no text attached to it (same for the original text)  "Subsequent spread across international borders within regions."  we left it as it is and in English, is that alright?

**Comment by cassiawag** [comment]
@benuraa, what do you mean? I'm not seeing it. I see the untranslated title in the table of contents, but it links to a normal page.

**Comment by benuraa** [comment]
@cassiawag sorry my bad, the title in the text was different than what it was in the text. Fixed now.

**Comment by cassiawag** [comment]
Thanks @benuraa!

**Comment by zeynephrc** [comment]
Thank you guys for the hardwork as usual!

**Comment by cassiawag** [comment]
Fantastic job, per usual. It's live here: https://nextstrain.org/narratives/ncov/sit-rep/tr/2020-04-10

Thank you, thank you -- take care!
