### ISSUE TITLE
Translate April 10 report into Spanish

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#29]
Hello @nextstrain/spanish!
 
The situation report from 2020-04-10  is ready to be translated to Spanish. This week’s report is a little bit shorter than usual but hopefully still informative :)
 
Branch to translate on: `sit-rep_es` 
 
File to translate: https://github.com/nextstrain/translations/blob/sit-rep_es/narratives/translations_ncov_sit-rep_es_2020-04-10.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_es/ncov/sit-rep/es/2020-04-10
 
Can someone please translate this Twitter post? The other option is me using Google Translate, which is probably not a good idea:
“This week’s situation report traces how the #COVID19 outbreak unfolded, month by month. It’s now available in Spanish: https://nextstrain.org/narratives/ncov/sit-rep/es/2020-04-10. 
 
Thank you @, @, and @ for the rapid translation!” 
 
**Logistics**
Please update the translations board as you work on the translation: 
https://github.com/orgs/nextstrain/projects/7
 
Please assign yourself to the translation if you’re working on it this week.
 
When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it! 
 
Feel free to use the [discussion board for your team](https://github.com/orgs/nextstrain/teams/spanish). Discussion boards are team specific, and unlike issues, they won’t disappear. It’s a good place to sort out translation workflows, post a dictionary for technical terms, etc.
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
Note: You may know of other great resources available in Spanish; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.
 
Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.  
 
**Thank you so very much all! Ya’ll are an incredible team to work with.**

**Comment by miparedes** [comment]
Hey y'all, happy to start it off with the first half through "cryptic transmission in Europe" and then can someone pick up the second half starting with "initial cryptic transmission in North America"?

**Comment by Cholokiwi** [comment]
Hi @Chjulian and @doyarzun00
I need to catch up on other work this weekend so I could proofread this week. 
Cheers, 
Roy

**Comment by doyarzun00** [comment]
No problem, I can pick up the 2nd half after @miparedes @Cholokiwi @Chjulian

**Comment by miparedes** [comment]
Hey all, just finished and pushed the 1st half -- it's all yours @doyarzun00 ! Thanks so much for all the teamwork week after week, it really is a privilege to work with you all!

**Comment by doyarzun00** [comment]
Ready for proofreading - some links need to be changed to the spanish ones. Sorry gotta run otherwise I would have done it myself! @Cholokiwi @miparedes

**Comment by Cholokiwi** [comment]
Hi team,

Proofreading done, the report is ready. Also, the translation for twitter is below:

"El reporte de esta semana hace un recuento de la evolución del #COVID19 mes a mes desde Diciembre del 2019. El reporte está disponible en español: https://nextstrain.org/narratives/ncov/sit-rep/es/2020-04-10."

Cheers,

Roy

**Comment by cassiawag** [comment]
It's published: https://nextstrain.org/narratives/ncov/sit-rep/es/2020-04-10

Thank you so much for translating these week after week @Cholokiwi, @doyarzun00, and @miparedes!
