### ISSUE TITLE
Translate April 10 report into Mandarin Chinese

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#33]
Hello @nextstrain/mandarin!
 
The situation report from 2020-04-10  is ready to be translated to Mandarin Chinese. This week’s report is a little bit shorter than usual but hopefully still informative :)
 
Branch to translate on: `sit-rep_zh` 
 
File to translate: https://github.com/nextstrain/translations/blob/sit-rep_zh/narratives/translations_ncov_sit-rep_zh_2020-04-10.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_zh/ncov/sit-rep/zh/2020-04-10
 
Can someone please translate this Twitter post? The other option is me using Google Translate, which is probably not a good idea:
“This week’s situation report traces how the #COVID19 outbreak unfolded, month by month. It’s now available in Chinese: https://nextstrain.org/narratives/ncov/sit-rep/zh/2020-04-10. 
 
Thank you @, @, and @ for the rapid translation!” 
 
**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7

Please assign yourself to the translation if you’re working on it this week.
 
When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it! 
 
Feel free to use the [discussion board for your team](https://github.com/orgs/nextstrain/teams/mandarin). Discussion boards are team specific, and unlike issues, they won’t disappear. It’s a good place to sort out translation workflows, post a dictionary for technical terms, etc.
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
Note: You may know of other great resources available in Mandarin; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.
 
Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.  
 
**Thank you so very much all! Ya’ll are an incredible team to work with.**

**Comment by lxy0107** [comment]
Hi all, I'm starting now. Anyone else who wants to join now can start from page 9.

**Comment by lxy0107** [comment]
Hi all, I'm preceding after text 9

**Comment by lxy0107** [comment]
Hi all, it's ready for proofreading now!:)

**Comment by fzhang12** [comment]
@lxy0107  Sorry I was kinda late to proofread your translation. It was PERFECT!! So I didn't change anything. I am very convinced that it is ready for publication.

**Comment by fzhang12** [comment]
translation for the tweet:
notice that I am adding Chinese common name of the virus to reach more population

“这周的状况报告向您阐述了 #新冠病毒 #新冠肺炎 #COVID19 疫情是如何从源头开始一个月一个月发展起来的。中文版现已更新： https://nextstrain.org/narratives/ncov/sit-rep/zh/2020-04-10

非常感谢 @3Xueying 和 @fengjun_zhang 对这周报告的及时高效翻译。”

**Comment by cassiawag** [comment]
Published! https://nextstrain.org/narratives/ncov/sit-rep/zh/2020-04-10

Thanks for a very excellent job, ladies. And thanks for adding in that name to the tweet. With those whatever will help it spread the word.
