### ISSUE TITLE
Translate April 10 report into Korean

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#34]
Hello @nextstrain/korean!
 
The situation report from 2020-04-10  is ready to be translated to Korean. This week’s report is a little bit shorter than usual but hopefully still informative :)
 
Branch to translate on: `sit-rep_ko` 
 
File to translate: https://github.com/nextstrain/translations/blob/sit-rep_ko/narratives/translations_ncov_sit-rep_ko_2020-04-10.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_ko/ncov/sit-rep/ko/2020-04-10
 
Can someone please translate this Twitter post? The other option is me using Google Translate, which is probably not a good idea:
“This week’s situation report traces how the #COVID19 outbreak unfolded, month by month. It’s now available in Korean: https://nextstrain.org/narratives/ncov/sit-rep/ko/2020-04-10. 
 
Thank you @, @, and @ for the rapid translation!” 
 
**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7

Please assign yourself to the translation if you’re working on it this week.
 
When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it! 
 
Feel free to use the [discussion board for your team](https://github.com/orgs/nextstrain/teams/korean). Discussion boards are team specific, and unlike issues, they won’t disappear. It’s a good place to sort out translation workflows, post a dictionary for technical terms, etc.
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
Note: You may know of other great resources available in Korean; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.
 
Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.  
 
**Thank you so very much all! Ya’ll are an incredible team to work with.**

**Comment by taehoonh** [comment]
Hi everyone,

Hope you stay strong and healthy. 04-10 report translation was complete. I would appreciate it if you start reviewing. Thanks!

Best,
TH

**Comment by mnkykm** [comment]
I reviewed the whole content and made a very minimal changes for they were almost perfect. Kudos to @taehoonh for such a rapid & precise translation.

Please use "팬데믹" for pandemic. 

@cassiawag This will do for Twitter:

"이번주 상황 보고서에서는 #COVID19 유행이 어떻게 펼쳐졌는지 월별로 추적해보았습니다. 이제 한국어로도 제공됩니다: https://nextstrain.org/narratives/ncov/sit-rep/ko/2020-04-10.

신속한 번역을 도와주신 @, @, @ 님께 감사드립니다!"

Pretty much good to go from my end.

**Comment by cassiawag** [comment]
Thank you @minkyuxyz and @taehoonh!  Very impressive.

@taehoonh -- let me know if it's ready to publish!

**Comment by taehoonh** [comment]
@cassiawag  @minkyuxyz My pleasure. Thank you so much for both as well. Guess it's ready to publish :)

**Comment by cassiawag** [comment]
It's published and tweeted: https://nextstrain.org/narratives/ncov/sit-rep/ko/2020-04-10

Thanks again! For future reports, can you make sure to translate the Abstract (heading) and Detailed Scientific Credit text (on last page)? Not a big deal that they got missed as I was able to pull them from a previous week's translation.
