### ISSUE TITLE
Translate April 10 report into Japanese

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#35]
Hello @nextstrain/japanese!
 
The situation report from 2020-04-10  is ready to be translated to Japanese. This week’s report is a little bit shorter than usual but hopefully still informative :)
 
Branch to translate on: `sit-rep_ja` 
 
File to translate: https://github.com/nextstrain/translations/blob/sit-rep_ja/narratives/translations_ncov_sit-rep_ja_2020-04-10.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_ja/ncov/sit-rep/ja/2020-04-10
 
Can someone please translate this Twitter post? The other option is me using Google Translate, which is probably not a good idea:
“This week’s situation report traces how the #COVID19 outbreak unfolded, month by month. It’s now available in Japanese: https://nextstrain.org/narratives/ncov/sit-rep/ja/2020-04-10. 
 
Thank you @, @, and @ for the rapid translation!” 
 
**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7
 
Please assign yourself to the translation if you’re working on it this week.
 
When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it! 
 
Feel free to use the [discussion board for your team](https://github.com/orgs/nextstrain/teams/japanese). Discussion boards are team specific, and unlike issues, they won’t disappear. It’s a good place to sort out translation workflows, post a dictionary for technical terms, etc.
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
Note: You may know of other great resources available in Japanese; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.
 
Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.  
 
**Thank you so very much all! Ya’ll are an incredible team to work with.**

**Comment by fzhang12** [comment]
Hi all, before you start translation this week, another volunteer willing to improve '系統樹の読み方' had different opinion on translation of 'transmission'. 
In the previous narratives, we took 「伝搬」all the time. Well, I searched myself but didn't find a reliable explanation of it. The new volunteer wanted to use 「感染」, I rejected because it is more close to what means infection. I am aware that Japanese media often use 「伝播」.
So I want to ask both of you, which one you agree with? 

You may use the [the discussion board](https://github.com/orgs/nextstrain/teams/japanese) to communicate. 
I will be offline for several hours and will read your opinions when I come back.

**Comment by tomoyuki-nezu** [comment]
Hello folks, I'm happy to be with you again.
I wrote it in discussion board. https://github.com/orgs/nextstrain/teams/japanese/discussions/1

**Comment by tomoyuki-nezu** [comment]
And I'll start translating now. This week it seems that the amount of text is small, so I'll translate it all, so please check the composition and translated words. I think that it will be finished at around 10AM(JST) because I eat breakfast before translating :)

**Comment by tomoyuki-nezu** [comment]
@satotake @fzhang12 The overall initial translation has been committed. Chaned all "伝搬" to "伝播".
Do clusters and samples need to be in Japanese?

I'm going out and we'll be back in the evening.

**Comment by satotake** [comment]
> Do clusters and samples need to be in Japanese?

They are ok to be written in katakana as `クラスター` or `サンプル` .
I had considered `クラスター` technical term before but they are used in news these days.

**Comment by satotake** [comment]
@tomoyuki-nezu @fzhang12 Done.

I wonder if [Ask a Scientist](https://covid19.fas.org/l/en) is proper noun. Is it site name?

**Comment by tomoyuki-nezu** [comment]
Oh, the site name (Corner name). It has been translated, but it is good to keep the original English text as corrected by @satotake . Thank you!!

**Comment by fzhang12** [comment]
Hi both, I have updated my changes to your translation. You have done a great job this week.
I edited some parts according to our discussion recently. You may now take a final look of the file.
If both of you are okay with it, I will later change the status to 'ready for publication' and create a pull request

**Comment by satotake** [comment]
Hi @fzhang12 
Thanks!
I changed 1 part. Could you check it please?
The other parts are ok.
waiting for @tomoyuki-nezu 's response

**Comment by tomoyuki-nezu** [comment]
Checked, No change from me. Thank you @fzhang12 @satotake 
It is good to translate "vulnerable group" to "重症化しやすいグループ".

@cassiawag Ready for publish :)

**Comment by tomoyuki-nezu** [comment]
Changed the status to "Ready for publication" and make a pull request.
https://github.com/nextstrain/translations/pull/49

Thank you all this weekend.
Have a safe days.

**Comment by cassiawag** [comment]
It's now published here: https://nextstrain.org/narratives/ncov/sit-rep/ja/2020-04-10 .

Thank you, thank you for diligence on this! Can anyone translate this Twitter post for me?

"This week’s situation report traces how the #COVID19 outbreak unfolded, month by month. It’s now available in Japanese: https://nextstrain.org/narratives/ncov/sit-rep/ja/2020-04-10.

Thank you @, @, and @ for the rapid translation!"

**Comment by tomoyuki-nezu** [comment]
@cassiawag Thank you for publishing. Is Japanese like this?

今週の状況報告では #COVID19 による感染拡大が毎月どのように広まっていったのかを追跡します。こちらから日本語でもご覧頂けるようになりました。
https://nextstrain.org/narratives/ncov/sit-rep/ja/2020-04-10
迅速な翻訳を行って頂いた @tommy_nezy, Takeshi Sato, @fengjun_zhang に感謝します。

**Comment by cassiawag** [comment]
Thanks @tomoyuki-nezu!
