### ISSUE TITLE
Translate April 10 report into Italian

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#36]
Hello @nextstrain/italian!
 
The situation report from 2020-04-10  is ready to be translated to Italian. This week’s report is a little bit shorter than usual but hopefully still informative :)
 
Branch to translate on: `sit-rep_it` 
 
File to translate: https://github.com/nextstrain/translations/blob/sit-rep_it/narratives/translations_ncov_sit-rep_it_2020-04-10.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_it/ncov/sit-rep/it/2020-04-10
 
Can someone please translate this Twitter post? The other option is me using Google Translate, which is probably not a good idea:
“This week’s situation report traces how the #COVID19 outbreak unfolded, month by month. It’s now available in Italian: https://nextstrain.org/narratives/ncov/sit-rep/it/2020-04-10. 
 
Thank you @, @, and @ for the rapid translation!” 
 
**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7
 
Please assign yourself to the translation if you’re working on it this week.
 
When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it! 
 
Feel free to use the [discussion board for your team](https://github.com/orgs/nextstrain/teams/italian). Discussion boards are team specific, and unlike issues, they won’t disappear. It’s a good place to sort out translation workflows, post a dictionary for technical terms, etc.
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
Note: You may know of other great resources available in Italian; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.
 
Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.  
 
**Thank you so very much all! Ya’ll are an incredible team to work with.**

**Comment by sarameiqi** [comment]
Hi @cassiawag, I'm on it.
Tomorrow morning (CEST) we can organize with other translators on the team's discussion board: https://github.com/orgs/nextstrain/teams/italian

Translated tweet:
Il rapporto di questa settimana che ricostruisce il modo in cui l'epidemia di #COVID19 si è sviluppata, mese dopo mese, è ora disponibile in italiano: https://nextstrain.org/narratives/ncov/sit-rep/it/2020-04-10.

If anybody wants to made some changes to my translation, please feel free to do it!

Best,
Sara

**Comment by al-epo** [comment]
Morning ! I am ready to start traslating! 
Who can work on it ? 
What do you want to use,  HackMD? if we work at different  time maybe is not so important using  it...
Meanwhile, I can start from Executive Summary 
Best, 
Alessia

**Comment by sarameiqi** [comment]
@al-epo I sent I proposal for how to organize the work in the discussion board: https://github.com/orgs/nextstrain/teams/italian

Let me know!

**Comment by sarameiqi** [comment]
@cassiawag I just discovered that I translated only a part of the tweet.
Please use this one for publication!

Il rapporto di questa settimana che ricostruisce il modo in cui l'epidemia di #COVID19 si è sviluppata, mese dopo mese, è ora disponibile in italiano: https://nextstrain.org/narratives/ncov/sit-rep/it/2020-04-10.
Grazie a @MEKlab, @ SaraMeiqi e @alice_ledda_ per la rapida traduzione!

**Comment by cassiawag** [comment]
No worries! I was just going to use Google translate for the thank's part b/c I think it's pretty accurate there. But this is better!

**Comment by cassiawag** [comment]
How's this translation coming? I know it was a little bit funky this weekend with the Easter holiday. Happy Easter btw!

**Comment by aliceLedda** [comment]
I think it's done!
Maybe they're were just waiting for my Twitter to submit @alice_ledda_
Sorry!
Alice

**Comment by al-epo** [comment]
Hello @cassiawag ! 
I did a last proofreading  it's ready to go for me!  
@sarameiqi is it ok for you?

**Comment by sarameiqi** [comment]
Hello everybody, 
last time I read it was ok, so I think we are ready to go!
Actually, with the Easter holidays I got twice the work I usually get on the weekends >.<
But at last we made it! ;)

**Comment by cassiawag** [comment]
It's live: https://nextstrain.org/narratives/ncov/sit-rep/it/2020-04-10

Thank you all so very much :)
