### ISSUE TITLE
Translate April 10 report into Dutch

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#42]
Hello @nextstrain/dutch!
 
The situation report from 2020-04-10  is ready to be translated to Dutch. This week’s report is a little bit shorter than usual but hopefully still informative :)
 
Branch to translate on: `sit-rep_nl` 
 
File to translate: https://github.com/nextstrain/translations/blob/sit-rep_nl/narratives/translations_ncov_sit-rep_nl_2020-04-10.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_nl/ncov/sit-rep/nl/2020-04-10
 
Can someone please translate this Twitter post? The other option is me using Google Translate, which is probably not a good idea:
“This week’s situation report traces how the #COVID19 outbreak unfolded, month by month. It’s now available in Dutch: https://nextstrain.org/narratives/ncov/sit-rep/nl/2020-04-10. 
 
Thank you @, @, and @ for the rapid translation!” 
 
**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7
 
Please assign yourself to the translation if you’re working on it this week.
 
When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it! 
 
Feel free to use the [discussion board for your team](https://github.com/orgs/nextstrain/teams/dutch). Discussion boards are team specific, and unlike issues, they won’t disappear. It’s a good place to sort out translation workflows, post a dictionary for technical terms, etc.
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
Note: You may know of other great resources available in Dutch; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.
 
Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.  
 
**Thank you so very much all! Ya’ll are an incredible team to work with.**

**Comment by roanvanscheppingen** [comment]
Limited time this morning. I'll bike my bike to Amsterdam (1,15 hours) (welcome to the Netherlands, where biking is faster than public transport. And will work on it again for a bit during the afternoon, if noone is faster!

**Comment by JiscaH** [comment]
I'll have time to work on it this afternoon too. If you let me know when you start, and I let you know when we start, we'll avoid translating the same slides :)

Geniet van je fietstocht! Het is er prachtig weer voor

**Comment by roanvanscheppingen** [comment]
Yes I'll do
Even hopen dat ik niet teveel tegenwind heb. Het is een oude stadsfiets die nog net niet uit elkaar valt van ellende, zonder versnelling. De Ronde Hoep is afgesloten voor wielrenners in groepen, maar ik gok dat ik er wel langs kan komen :)

**Comment by JiscaH** [comment]
Tegenwind op 'n fiets zonder versnellingen bouwt karakter zeggen ze ;) Klinkt niet alsof ze je voor een wielrenner gaan vergissen!

**Comment by JiscaH** [comment]
Ik ga aan de slag.

**Comment by JiscaH** [comment]
All done!

**Comment by JiscaH** [comment]
@cassiawag translation of the twitter message:

"Het situatierapport van deze week schetst hoe de #COVID19 zich ontvouwde, maand na maand. Nu beschikbaar in het Nederlands: https://nextstrain.org/narratives/ncov/sit-rep/nl/2020-04-10.

Met dank aan @, @, and @ voor de snelle vertaling!”

**Comment by JSHuisman** [comment]
Ik ga er nu doorheen

**Comment by JSHuisman** [comment]
I think it's ready to be published!

**Comment by cassiawag** [comment]
Published! https://nextstrain.org/narratives/ncov/sit-rep/nl/2020-04-10

I say it very week, but thank you so, so much. take care!
