### ISSUE TITLE
Translate April 10 report into Arabic

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#43]
Hello @nextstrain/arabic!
 
The situation report from 2020-04-10  is ready to be translated to Arabic. This week’s report is a little bit shorter than usual but hopefully still informative :)
 
Branch to translate on: `sit-rep_ar` 
 
File to translate: https://github.com/nextstrain/translations/blob/sit-rep_ar/narratives/translations_ncov_sit-rep_ar_2020-04-10.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_ar/ncov/sit-rep/ar/2020-04-10
 
Can someone please translate this Twitter post? The other option is me using Google Translate, which is probably not a good idea:
“This week’s situation report traces how the #COVID19 outbreak unfolded, month by month. It’s now available in Arabic: https://nextstrain.org/narratives/ncov/sit-rep/ar/2020-04-10. 
 
Thank you @, @, and @ for the rapid translation!” 
 
**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7
 
Please assign yourself to the translation if you’re working on it this week.
 
When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it! 
 
Feel free to use the [discussion board for your team](https://github.com/orgs/nextstrain/teams/arabic). Discussion boards are team specific, and unlike issues, they won’t disappear. It’s a good place to sort out translation workflows, post a dictionary for technical terms, etc.
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
Note: You may know of other great resources available in Arabic; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.
 
Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.  
 
**Thank you so very much all! Ya’ll are an incredible team to work with.**

**Comment by SalehA74** [comment]
Here is the translation for the twitter post into Arabic: 
“يتتبع تقرير هذا الاسبوع عن #COVID19 لكيفية تكشف اندلاع الوباء شهراً بشهر. وهو متوفر حالياً باللغة العربية. https://nextstrain.org/narratives/ncov/sit-rep/ar/2020-04-10.

شكراً جزيلاً لكل من @DrSalehAhmad و @biofadialnaji  على الترجمة السريعة.

**Comment by cassiawag** [comment]
Excellent work @SalehA74 & @falnaji. It's published here:  https://nextstrain.org/narratives/ncov/sit-rep/ar/2020-04-10. Take care!
