### ISSUE TITLE
Weblate translation platform

### ISSUE THREAD

**Issue by comradekingu** [nextstrain/translations#53]
Maybe this could be added to Hosted Weblate, which has markdown support,
and a huge community. GitHub login is supported.

https://weblate.org/hosting/

**What language would you like the situation reports to be translated into?** 
nb_NO

**Are you available to help translate?** (Either way is alright, just let us know! :)
Yes.

**Comment by cassiawag** [comment]
Hi @comradekingu, would you explain weblate in more detail? I'm not familiar with it.

**Comment by comradekingu** [comment]
It is a translation platform. Projects are added, continuously fed changes, receiving translations in return. Try it https://hosted.weblate.org/projects/sandbox/ :)
Send a request here https://weblate.org/hosting/ or self-host.

**Comment by cassiawag** [comment]
Thanks for the heads up! Interesting site; I think we'll pass for now though.
