### ISSUE TITLE
Translate April 17 report into Turkish

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#55]
Hello @nextstrain/turkish!
 
The situation report from 2020-04-17  is ready to be translated to Turkish. Sorry it’s a little late this week. The report focuses on the USA. We do have a significant linguistic diversity here, but I’ll let you decide if you want to translate it. In general, I do think it’s worth understanding how the virus spreads in other regions of the world, but I’m not doing the hard work of translation.
 
Branch to translate on: `sit-rep_tr` 
 
File to translate: https://github.com/nextstrain/translations/blob/sit-rep_tr/narratives/translations_ncov_sit-rep_tr_2020-04-17.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_tr/ncov/sit-rep/tr/2020-04-17
 
Twitter post to translate: 
“This week’s #COVID19 situation report covers the outbreak in the United States. It is now available in Turkish. Thank you @, @, and @ for the rapid translation.” 
 
**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7
 
Please assign yourself to the translation if you’re working on it this week.
 
When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it! 
 
Discussion board for your team is here: https://github.com/orgs/nextstrain/teams/turkish
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
Note: You may know of other great resources available in Turkish; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.
 
Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.  
 
**As always a hearty thank you! I am really enjoying working with you all, even if it’s just digitally. Take care!**

**Comment by benuraa** [comment]
Hi @zeynephrc! I will start translating from  "Midwest outbreaks were seeded by many introductions" to the end and check with you where you are at.

**Comment by Cagataytarhan** [comment]
Following you @benuraa

**Comment by erenada** [comment]
Hi all,

I will not be able to participate in this week's translation due to my busy schedule. Sorry about this :/ Cok sagolun devam ettirdiginiz icin, ellerinize saglik!

**Comment by benuraa** [comment]
No worries @erenada kolay gelsin!

**Comment by zeynephrc** [comment]
Hey all,

As far as I saw, the report is almost done! So, I'll be proofreading this time if it's okay for everybody.

Feel free to join me.

Thank you!

@erenada kolay gelsin:)

**Comment by benuraa** [comment]
@zeynephrc that woud be perfect, give me a wee while to finalise it and I will give you a shout. 

Cheers!

**Comment by benuraa** [comment]
@zeynephrc all yours. @Cagataytarhan and myself are done :)

**Comment by zeynephrc** [comment]
Hello,

I finished the proofreading and did tiny tiny changes. Thanks everybody!

@cassiawag I think we're done.

**Comment by zeynephrc** [comment]
By the way, @cassiawag ,  Twitter post in Turkish:

Bu haftanın #COVID19 durum raporu ABD'deki salgını içeriyor. Şu anda Türkçe haliyle yayında! @zharcanoglu, @benuraa ve @cagataytarhan 'a hızlı çevirileri için teşekkür ederiz.

**Comment by cassiawag** [comment]
Published and tweeted: https://nextstrain.org/narratives/ncov/sit-rep/tr/2020-04-17

Thanks for another efficient translation!
