### ISSUE TITLE
Translate April 17 report into Spanish

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#56]
Hello @nextstrain/spanish!
 
The situation report from 2020-04-17  is ready to be translated to Spanish. Sorry it’s a little late this week. The report focuses on the USA. We do have a significant linguistic diversity here, but I’ll let you decide if you want to translate it. In general, I do think it’s worth understanding how the virus spreads in other regions of the world, but I’m not doing the hard work of translation.
 
Branch to translate on: `sit-rep_es` 
 
File to translate: https://github.com/nextstrain/translations/blob/sit-rep_es/narratives/translations_ncov_sit-rep_es_2020-04-17.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_es/ncov/sit-rep/es/2020-04-17
 
Twitter post to translate: 
“This week’s #COVID19 situation report covers the outbreak in the United States. It is now available in Spanish. Thank you @, @, and @ for the rapid translation.” 
 
**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7
 
Please assign yourself to the translation if you’re working on it this week.
 
When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it! 
 
Discussion board for your team is here: https://github.com/orgs/nextstrain/teams/spanish
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
Note: You may know of other great resources available in Spanish; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.
 
Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.  
 
**As always a hearty thank you! I am really enjoying working with you all, even if it’s just digitally. Take care!**

**Comment by miparedes** [comment]
Hey all! It's a busy weekend but I can do the first half through "Intermingling of cases from all 5 NYC boroughs", if someone wants to take the second half. Im going to try to work on it tonight but might not get to it until tomorrow morning.

**Comment by doyarzun00** [comment]
Hi, can do proofreading this time. Bit tight on time.
D

**Comment by Cholokiwi** [comment]
Hi @miparedes, @doyarzun00 ,
I'll translate the second part. Hard times ahead for the outbreak in Latin-America :(
Cheers,

Roy

**Comment by miparedes** [comment]
sorry for the delay, everyone. Just finished and pushed the first half!

**Comment by Cholokiwi** [comment]
Hi all,
Second part is done. Ready for proofreading.
Cheers,

Roy

**Comment by doyarzun00** [comment]
Proofreading ready. Here's the translation of the tweet
'El reporte #COVID19 de esta semana es acerca del brote en EEUU. Disponible ahora en español. Gracias a @miguelp1120, @CMroycostilla, and @doyarzunrod por la rápida traducción.'

@miparedes @Cholokiwi @cassiawag

**Comment by cassiawag** [comment]
Published and tweeted: https://nextstrain.org/narratives/ncov/sit-rep/es/2020-04-17

Thank you again for an all-star effort!
