### ISSUE TITLE
Translate April 17 report into Russian

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#57]
Hello @nextstrain/russian!
 
The situation report from 2020-04-17  is ready to be translated to Russian. Sorry it’s a little late this week. The report focuses on the USA. We do have a significant linguistic diversity here, but I’ll let you decide if you want to translate it. In general, I do think it’s worth understanding how the virus spreads in other regions of the world, but I’m not doing the hard work of translation.
 
Branch to translate on: `sit-rep_ru` 
 
File to translate: https://github.com/nextstrain/translations/blob/sit-rep_ru/narratives/translations_ncov_sit-rep_ru_2020-04-17.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_ru/ncov/sit-rep/ru/2020-04-17
 
Twitter post to translate: 
“This week’s #COVID19 situation report covers the outbreak in the United States. It is now available in Russian. Thank you @, @, and @ for the rapid translation.” 
 
**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7
 
Please assign yourself to the translation if you’re working on it this week.
 
When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it! 
 
Discussion board for your russian is here: https://github.com/orgs/nextstrain/russians/russian
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate Russian version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
Note: You may know of other great resources available in Russian; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.
 
Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.  
 
**As always a hearty thank you! I am really enjoying working with you all, even if it’s just digitally. Take care!**

**Comment by frogtraveler** [comment]
I can't open the Discussion board following the link in this post. Could someone please send me a working link?

**Comment by dtaliun** [comment]
> I can't open the Discussion board following the link in this post. Could someone please send me a working link?

I believe this is the right link https://github.com/orgs/nextstrain/teams/russian

**Comment by frogtraveler** [comment]
That worked, thank you @dtaliun !

**Comment by frogtraveler** [comment]
@cassiawag I just noticed that the link on how to read phylogenetic trees leads to the English version of the document. I wasn't sure it is replaced with Russian version of the document later, but I figured I'll let you know. Thanks!

**Comment by frogtraveler** [comment]
@irina95511 Could you please review?

**Comment by frogtraveler** [comment]
@cassiawag We still need to review the translation, but here is the twit in Russian:
На этой неделе Ситуационный доклад о #COVID19 касается Соединённых Штатов Америки. Доклад теперь доступен на русском языке. Спасибо @varvarakozyreva, Daniel Taliun и @MEKlab за быстрый перевод.

**Comment by irina95511** [comment]
@frogtraveler @dtaliun I can have a look within 4ish hours! Sorry that I was very busy last weekend and have not helped earlier!

**Comment by irina95511** [comment]
@frogtraveler @dtaliun Great job! Again, I did not have much to do. 
@cassiawag The reviewing is done, all good!

**Comment by cassiawag** [comment]
Published and tweeted: https://nextstrain.org/narratives/ncov/sit-rep/ru/2020-04-17

Thank you all!
