### ISSUE TITLE
Translate April 17 report into Portuguese

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#58]
Hello @nextstrain/portuguese!
 
The situation report from 2020-04-17  is ready to be translated to Portuguese. Sorry it’s a little late this week. The report focuses on the USA. We do have a significant linguistic diversity here, but I’ll let you decide if you want to translate it. In general, I do think it’s worth understanding how the virus spreads in other regions of the world, but I’m not doing the hard work of translation.
 
Branch to translate on: `sit-rep_pt` 
 
File to translate: https://github.com/nextstrain/translations/blob/sit-rep_pt/narratives/translations_ncov_sit-rep_pt_2020-04-17.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_pt/ncov/sit-rep/pt/2020-04-17
 
Twitter post to translate: 
“This week’s #COVID19 situation report covers the outbreak in the United States. It is now available in Portuguese. Thank you @, @, and @ for the rapid translation.” 
 
**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7
 
Please assign yourself to the translation if you’re working on it this week.
 
When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it! 
 
Discussion board for your team is here: https://github.com/orgs/nextstrain/teams/portuguese
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
Note: You may know of other great resources available in Portuguese; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.
 
Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.  
 
**As always a hearty thank you! I am really enjoying working with you all, even if it’s just digitally. Take care!**

**Comment by 7glaucio** [comment]
Hello, Cassia. (@cassiawag )

I had some free time this afternoon, so I finally translated it. I don't know who is available to proofread this time, but it's already there. 

I think is important indeed to translate US info, since there's a lot of Brazilian people living here, or even interested on this information. Actually, not only Brazilian. I know people from Portugal, Cape Verde, and Mozambique here in Boston. They all speak Portuguese, as well.

**Comment by cassiawag** [comment]
Thank you @7glaucio! @andersonbrito or @EricaBarroso, are either of you available to do a review?

**Comment by andersonbrito** [comment]
Hi @cassiawag, I won't be able to review it this time, sorry.

**Comment by EricaBarroso** [comment]
Me neither for this time, sorry.

**Comment by cassiawag** [comment]
@amadotalita & @miguelbio, hello! Anderson Brito gave me your GitHub handles and said you might be interested in helping with Portuguese translations of the Nextstrain situation reports. Thanks for your willingness to help out! We definitely welcome it.

I've sent you both a GitHub invitation to join Nextstrain, specifically the Translators and Portuguese teams. Please accept that invitation. Once you do so, you should have access to push to branches in this repo. You'll also then have access to the [Portuguese discussion board](https://github.com/orgs/nextstrain/teams/portuguese) which is a nice place to coordinate with other translators outside of the Issues. Some teams are using this as a place to post dictionary's for the technical terms.

Weekly situation reports are published every Friday around 5 p.m. PDT, and we try to publish translations by Monday morning PDT. Often the translations are published sooner, but sometimes they're later. Every translation must have at least two people's eyes on it and one of those people needs to have a background in phylogenetics. 

For the Portuguese translations, Glaucio has been doing a fabulous job of the base translation, and then another person Erica or Anderson has been reviewing. I'll tag you in an issue when the report is ready to be translated, please just chime in on that issue if and how you're able to help that week. 

To help you ease you into translations, we have a situation report from April 17 on the outbreak in the United States that needs a proofread. Unfortunately, nobody was able to review the base translation, so we could not publish a Portuguese version of it. Can you please review the translation? All of the information should be in the issue above.

Please don't hesitate to ask any questions you have. We REALLY appreciate your help! Thank you :)

**Comment by cassiawag** [comment]
@amadotalita & @miguelbio, hello! Just wanted to check-in and see if you were able to get started on the above. Thank you for the help.

**Comment by amadotalita** [comment]
Oh, hey! Yes, I started the revision, I just didn't have time to finish it. Sorry about that, I'm scheduled to continue tomorrow morning. It's that ok?

**Comment by amadotalita** [comment]
Oh, hey! Yes, I started the revision, I just didn't have time to finish it. Sorry about that, I'm schedule

**Comment by cassiawag** [comment]
Yup, that's just fine @amadotalita, no rush. I just wanted to check-in and see if you'd gotten access or had any process questions.

**Comment by amadotalita** [comment]
Hi @cassiawag, I just finished reviewing this translation and did minor corrections. Should I wait for another person to review it before create a pull request?

**Comment by cassiawag** [comment]
Thank you @amadotalita! I don't think so, it's already had Glaucio's eyes on it and our policy is two people. Go ahead and create the PR

**Comment by cassiawag** [comment]
Thanks @amadotalita! I added your name to the translators list and published it here: https://nextstrain.org/narratives/ncov/sit-rep/pt/2020-04-17
