### ISSUE TITLE
Translate April 3 COVID-19 report into Greek

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#6]
Hello @akifoss @codergr !
 
The situation report from 2020-04-03  is ready to be translated to Greek. 
Branch to translate on: `sit-rep_el` 
File to translate: https://github.com/nextstrain/translations/blob/sit-rep_el/narratives/translations_ncov_sit-rep_el_2020-04-03.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!
Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_el/ncov/sit-rep/el/2020-04-03
 
**Logistics**
Once you’ve accepted my invitation to join the Nextstrain organization and the `translations` repo, you should have access to push to branches. Ping me if you’re having problems.
 
Please update the translations board as you work on the translation: https://github.com/nextstrain/translations/projects/1
 
Please assign yourself to the translation if you’re working on it this week.
 
When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it! 
 
Use the [discussion board for your team](https://github.com/orgs/nextstrain/teams/greek). Discussion boards are a place for you to communicate together, and unlike issues, they won’t disappear. It’s a good place to sort out translation workflows, post a dictionary for technical terms, whatever you need as a team.
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Greek-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Greek; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in the field. Although if you have more, that’s fine too.
 
Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.  
 
**Thank you so very much! It’s an honor to fight the pandemic with you. I continue to hope you and your loved ones are well.**

**Comment by ghost** [comment]
@cassiawag Have some time will start tomorrow morning and share for review @akifoss as soon as possible

**Comment by akifoss** [comment]
@codergr Have you already started? I am also available now. Let's use this: https://hackmd.io/af8_3BI2QZy_6K7JIM2s0g

**Comment by ghost** [comment]
> @codergr Have you already started? I am also available now. Let's use this: https://hackmd.io/af8_3BI2QZy_6K7JIM2s0g

Super I can translate in the move with this from my iPhone ! Thanks @akifoss !

**Comment by ghost** [comment]
Please proceed as much as you can and will update later at hackmd  deltas/gaps Have a nice day !

**Comment by akifoss** [comment]
@codergr I am done with translating the report, everything looks good on my side, I also checked the preview. However, there seems to be an issue which is inherited from the original report. Our lines 69 & 71, original report in english lines 67 & 69. If this issue is resolved or if this visualization was intended and is correct, then you have a go from my side to make a pull request.

**Comment by ghost** [comment]
@akifoss: Gr8 job!
- did some small corrections and some minor edits with links added el when needed ( sit-rep/**el** )
- with regards comments 69/71 I think it renders with next strain rendering engine since it show fine in next strain page.

So LGTM I haven't used hackmd before for pull, is this something you know how we can do?

**Comment by ghost** [comment]
@cassiawag from translation we are ok we have double checked I think you can move it to ready for publication after passes your tests. Keep safe !

**Comment by cassiawag** [comment]
It's published here: https://nextstrain.org/narratives/ncov/sit-rep/el/2020-04-03!

Thanks @akifoss & @codergr for another good translation.
