### ISSUE TITLE
Translate April 17 report into Japanese

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#62]
Hello @nextstrain/japanese!
 
The situation report from 2020-04-17  is ready to be translated to Japanese. Sorry it’s a little late this week. The report focuses on the USA. We do have a significant linguistic diversity here, but I’ll let you decide if you want to translate it. In general, I do think it’s worth understanding how the virus spreads in other regions of the world, but I’m not doing the hard work of translation.
 
Branch to translate on: `sit-rep_ja` 
 
File to translate: https://github.com/nextstrain/translations/blob/sit-rep_ja/narratives/translations_ncov_sit-rep_ja_2020-04-17.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_ja/ncov/sit-rep/ja/2020-04-17
 
Twitter post to translate: 
“This week’s #COVID19 situation report covers the outbreak in the United States. It is now available in Japanese. Thank you @, @, and @ for the rapid translation.” 
 
**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7
 
Please assign yourself to the translation if you’re working on it this week.
 
When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it! 
 
Discussion board for your team is here: https://github.com/orgs/nextstrain/teams/japanese
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
Note: You may know of other great resources available in Japanese; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.
 
Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.  
 
**As always a hearty thank you! I am really enjoying working with you all, even if it’s just digitally. Take care!**

**Comment by tomoyuki-nezu** [comment]
Hello all.
It takes about an hour so I will translate it. If there is another person who can translate, please start from "California" section.

**Comment by tomoyuki-nezu** [comment]
Translated to NYC section and committed.
I didn't understand the translation, so I wrote an entry here.
https://github.com/orgs/nextstrain/teams/japanese/discussions/3

**Comment by tomoyuki-nezu** [comment]
I have a little time more, so I'll do it to the end.

**Comment by tomoyuki-nezu** [comment]
@satotake @fzhang12 Initial translation was done until the end. Please review and fix.

**Comment by satotake** [comment]
@tomoyuki-nezu 
Thanks for your hard work 👍 

Done.
- Modified 2 parts as commit (nits)
- Replied to your discussion
- Created new thread about `span the genetic diversity...`

Please check it.

@fzhang12 I am looking forward to your opinion and review

**Comment by fzhang12** [comment]
Thanks for your excellent job @satotake @tomoyuki-nezu 
I did not introduce too many changes to your translation.
For both fo the discussion in our board, I would like to stay with what they look like right now.
Happy working with you both :)

Twitter post to translate:
“今週の状況報告では #COVID19 によるアメリカでの感染拡大を追跡します。こちらから日本語でもご覧頂けるようになりました。

迅速な翻訳を行って頂いた @tommy_nezy , Takeshi Sato, @fengjun_zhang に感謝します。”

**Comment by cassiawag** [comment]
Published and tweeted: https://nextstrain.org/narratives/ncov/sit-rep/ja/2020-04-17?f_country=USA

Thank you so very much, @fzhang12, @tomoyuki-nezu, and @satotake :)
