### ISSUE TITLE
Translate April 17 report into Italian

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#63]
Hello @nextstrain/italian!
 
The situation report from 2020-04-17  is ready to be translated to Italian. Sorry it’s a little late this week. The report focuses on the USA. We do have a significant linguistic diversity here, but I’ll let you decide if you want to translate it. In general, I do think it’s worth understanding how the virus spreads in other regions of the world, but I’m not doing the hard work of translation.
 
Branch to translate on: `sit-rep_it` 
 
File to translate: https://github.com/nextstrain/translations/blob/sit-rep_it/narratives/translations_ncov_sit-rep_it_2020-04-17.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_it/ncov/sit-rep/it/2020-04-17
 
Twitter post to translate: 
“This week’s #COVID19 situation report covers the outbreak in the United States. It is now available in Italian. Thank you @, @, and @ for the rapid translation.” 
 
**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7
 
Please assign yourself to the translation if you’re working on it this week.
 
When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it! 
 
Discussion board for your team is here: https://github.com/orgs/nextstrain/teams/italian
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
Note: You may know of other great resources available in Italian; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.
 
Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.  
 
**As always a hearty thank you! I am really enjoying working with you all, even if it’s just digitally. Take care!**

**Comment by sarameiqi** [comment]
Hi all, I thihnk that it is useful to translate also into Italian, people can decide for themselves if they want to read or not. It is possible that this translation is going to take some more time, but I think this is not a real problem!
Thank you @cassiawag and the whole team for producing these reports!

**Comment by al-epo** [comment]
I agree!

**Comment by aliceLedda** [comment]
I agree too!
How do we do?

**Comment by al-epo** [comment]
I wrote here https://github.com/orgs/nextstrain/teams/italian

**Comment by sarameiqi** [comment]
HI @cassiawag we are ready for publication, but for some reason I can't move it to the "ready for publication" column.

Do you need help with the translation of the tweet?

**Comment by cassiawag** [comment]
@sarameiqi, yes please!

"This week’s #COVID19 situation report covers the outbreak in the United States. It is now available in Italian. Thank you @, @, and @ for the rapid translation."

**Comment by sarameiqi** [comment]
Here it is!

Il rapporto sulla situazione del #COVID19 di questa settimana, che si occupa dell'epidemia negli Stati Uniti, è ora disponibile in italiano. Grazie @ Grazie a @MEKlab ,@ SaraMeiqi , e @alice_ledda_ per la rapida traduzione!

**Comment by cassiawag** [comment]
Published and tweeted! Thank you SO MUCH ladies!
