### ISSUE TITLE
Translate April 17 report into German

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#66]
Hello @nextstrain/german!
 
The situation report from 2020-04-17  is ready to be translated to German. Sorry it’s a little late this week. The report focuses on the USA. We do have a significant linguistic diversity here, but I’ll let you decide if you want to translate it. In general, I do think it’s worth understanding how the virus spreads in other regions of the world, but I’m not doing the hard work of translation.
 
Branch to translate on: `sit-rep_de` 
 
File to translate: https://github.com/nextstrain/translations/blob/sit-rep_de/narratives/translations_ncov_sit-rep_de_2020-04-17.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_de/ncov/sit-rep/de/2020-04-17
 
Twitter post to translate: 
“This week’s #COVID19 situation report covers the outbreak in the United States. It is now available in German. Thank you @, @, and @ for the rapid translation.” 
 
**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7
 
Please assign yourself to the translation if you’re working on it this week.
 
When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it! 
 
Discussion board for your team is here: https://github.com/orgs/nextstrain/teams/german
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
Note: You may know of other great resources available in German; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.
 
Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.  
 
**As always a hearty thank you! I am really enjoying working with you all, even if it’s just digitally. Take care!**

**Comment by astridgall** [comment]
Balancing time it would take to translate this and value (as the report is on the US) I won't be working on it this week. Looking forward to a new report on Europe though and happy to help with that!

**Comment by Hirthe** [comment]
@astridgall I would have time to translate it :) Would you have time proofreading it? :)

**Comment by astridgall** [comment]
@Hirthe Yes, I can proofread layer today. Let me know when you are finished.

**Comment by Hirthe** [comment]
@astridgall I am done :) Have a nice Sunday evening :)

**Comment by astridgall** [comment]
@Hirthe Thanks! Enjoy the rest of your Sunday too! I'll proofread now

**Comment by astridgall** [comment]
@cassiawag This is ready. Here the tweet:

Diese Woche behandelt der #COVID19 Lagebericht den Ausbruch in den Vereinigten Staaten. Er ist nun in Deutsch verfügbar. Vielen Dank an @AstridGAGall und Elisabeth Hirth für die schnelle Übersetzung.

**Comment by cassiawag** [comment]
Published and tweeted: https://nextstrain.org/narratives/ncov/sit-rep/de/2020-04-17

Thank you both so much!!
