### ISSUE TITLE
Translate April 3 COVID-19 report in Italian

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#8]
Hello @al-epo @sarameiqi  @whispererindarkness @aliceLedda !
 
The situation report from 2020-04-03  is ready to be translated to Italian. 
Branch to translate on: `sit-rep_it` 
File to translate: https://github.com/nextstrain/translations/blob/sit-rep_it/narratives/translations_ncov_sit-rep_it_2020-04-03.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!
Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_it/ncov/sit-rep/it/2020-04-03
 
**Logistics**
Once you’ve accepted my invitation to join the Nextstrain organization and the `translations` repo, you should have access to push to branches. Ping me if you’re having problems.
 
Please update the translations board as you work on the translation: https://github.com/nextstrain/translations/projects/1
 
Please assign yourself to the translation if you’re working on it this week.
 
When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it! 
 
Use the [discussion board for your team](https://github.com/orgs/nextstrain/teams/italian). Discussion boards are a place for you to communicate together, and unlike issues, they won’t disappear. It’s a good place to sort out translation workflows, post a dictionary for technical terms, whatever you need as a team.
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Italian-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Italian; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in the field. Although if you have more, that’s fine too.
 
Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.  
 
**Thank you so very much! It’s an honor to fight the pandemic with you. I continue to hope you and your loved ones are well.**

**Comment by al-epo** [comment]
Morning all @sarameiqi @whispererindarkness @aliceLedda and  @cassiawag ! I set up an HackMD file so we can work together on it.

Here the link:  https://hackmd.io/@6tiiAnaXQFqzAzll66fGdA/HyaGY6HvU

I sign up via gitHub, it is quite straightforward. Please let me know if you have issue with it!

best,

**Comment by sarameiqi** [comment]
Hi @al-epo , you did great!
If you like, this week I can devote myself to the final proofreading (especially if you can manage to translate the whole text by Sunday afternoon).
Please feel free to use the American keyboard, I will adjust accents during the proofreading. 
If you have any problems and cannot translate the whole text by Sunday afternoon, I can do whetever you didn't translate.

What do you think?
Best

**Comment by al-epo** [comment]
Hi @sarameiqi ! Thanks!
Perfect for me! I should  finish this afternoon, I will keep you posted. I have an Italian  keyboard  so accents should  be ok but a double check  is always  welcome :-) 
For length  limits I had to left out of the HackMD file the list of Universities  and Institutions  that contributed so what we could  do at the end of the proofreading it is just copy and past back the document on github. Unless  I find some other smarted ways..any ideas?

best,

**Comment by aliceLedda** [comment]
Ciao care/o!
Quindi io devo solo rileggere?
Fantastico, grazie!
Alice

**Comment by al-epo** [comment]
Ciao !
Io ho finito, ho una lista di parole che vorrei discutere  con voi ma ora ho bisogno di una pausa. 
Se usate il link 
https://hackmd.io/@6tiiAnaXQFqzAzll66fGdA/HyaGY6HvU
potete iniziare a commentare 
O preferite un copia e incolla su github? 
fatemi sapere! Mi riattivo tra una mezz’ora

**Comment by sarameiqi** [comment]
@al-epo grazie mille, per me puoi lasciare su hackmd, ma dipende @whispererindarkness come si trova...
Quando vuoi, le domande e i dubbi postali qui: https://github.com/orgs/nextstrain/teams/italian

**Comment by al-epo** [comment]
@sarameiqi @aliceLedda @whispererindarkness ho postato su  https://github.com/orgs/nextstrain/teams/italian
;-)

**Comment by al-epo** [comment]
@sarameiqi  @aliceLedda  @whispererindarkness  ho modificato alcune frasi seguendo i commenti di @sarameiqi e @aliceLedda. 
Potreste dare una rilettura ?  Se no, lo faccio io più tardi

**Comment by al-epo** [comment]
@cassiawag We are bit confused by the sentence: 

"We can't be sure if the linked sequences represent community transmission in Austria or travel partners linking together after exposure to the same strain."

"travel partners" is intended  as other people you travel with ? 
it sounds to me that "travel patterns "  such as paths that come in contact would be more clear . 
Or am I misunderstanding the sentence ? 

Thanks a lot!

**Comment by sarameiqi** [comment]
Ciao, scusate se sono sparita, ma è stata una domenica un po' impegnata.
Se la traduzione è finita, la riprendo da hackm e incollo su github, correggendo direttamente quello che mi sembra ok. Appena ho finito, magari leggete dalla preview, così vedete se è tutto a posto.

@al-epo @aliceLedda ok per voi?

**Comment by al-epo** [comment]
@sarameiqi Si grazie! Ti ho risposto anche sulla discussione  :-)

**Comment by cassiawag** [comment]
@al-epo, thanks for the question. We meant "__samples from__ travel partners linking together after exposure to..." Travel partners does indeed refer to people you travel with.

**Comment by cassiawag** [comment]
Does that make sense?

**Comment by al-epo** [comment]
@cassiawag  Thanks for your answer, I got it now!

**Comment by sarameiqi** [comment]
@al-epo please modify it on hackm so I go straight to the review on the github file.

**Comment by al-epo** [comment]
@sarameiqi  doing it

**Comment by al-epo** [comment]
@sarameiqi  I updated  the github file now

**Comment by sarameiqi** [comment]
Se potete, non fate più modifiche sul file finché non vi scrivo, così ho il tempo di rivedere tutto senza committare ogni 5 minuti. ;)

**Comment by sarameiqi** [comment]
Ho committato, per me è pronto, chi può dare una letta direttamente da questo link?
https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_it/ncov/sit-rep/it/2020-04-03

**Comment by al-epo** [comment]
posso leggere tra una mezz’ora,  ok?

**Comment by al-epo** [comment]
@sarameiqi  non riesco ad accede al link, dice che c'è un errore e non è possibile caricare la pagina ...

**Comment by al-epo** [comment]
@sarameiqi  non ho letto usando il link, ma ho letto la pagina con il testo tradotto: per me va bene. 
Grazie per aver controllato! E scusa, mi ero dimenticata  di tradurre  l'abstract.

**Comment by sarameiqi** [comment]
Figurati, è stato un buon lavoro di squadra!
@aliceLedda @whispererindarkness se volete leggere e commentare fateci sapere, se no do il via per la pubblicazione!

**Comment by aliceLedda** [comment]
Io do il via!

**Comment by sarameiqi** [comment]
@aliceLedda aggiungi il tuo nome e il tuo twitter!

**Comment by sarameiqi** [comment]
@cassiawag we are ready for publication, I added @aliceLedda name's myself.

Thank you, great job also this week! ;)
Sara

**Comment by aliceLedda** [comment]
Sorry Sara!
Thanks!
Great Job!!
Alice

**Comment by cassiawag** [comment]
It's live here: https://nextstrain.org/narratives/ncov/sit-rep/it/2020-04-03

Great job all. Thanks for the dedication to making such an excellent translation. Please share it widely
