### ISSUE TITLE
Translate April 24 covid report into Italian

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#89]
Hello @nextstrain/italian!

The situation report from 2020-04-24 is ready to be translated to Italian. The report focuses on Africa. We chose this region this week as the outbreaks in African nations are very important to understand and do not seem to be getting a lot of press. Please translate the Twitter post below! It is a bummer when the translation is great, but people do not know that because I used Google translate for the Twitter post.

Branch to translate on: `sit-rep_it`

File to translate: https://github.com/nextstrain/translations/blob/sit-rep_it/narratives/translations_ncov_sit-rep_it_2020-04-24.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!

Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_it/ncov/sit-rep/it/2020-04-24

Twitter post to translate:
“We focus on Africa this week in our #COVID19 situation report. The report is now available in Italian. Thank you @, @, and @ for the rapid translation."

**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7

Please assign yourself to the translation if you’re working on it this week.

When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it!

Discussion board for your team is here: https://github.com/orgs/nextstrain/teams/italian

**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`.

Please add your name under `translators:` with new line, tab, and dash, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.

Note: You may know of other great resources available in Italian; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.

At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.

Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.

**Thank you all so, so much! :)**

**Comment by sarameiqi** [comment]
Il rapporto sul COVID19 di questa settimana si concentra sull'Africa ed è ora disponibile in Italiano. Grazie a @MEKlab, @ SaraMeiqi e @alice_ledda_ per la rapida traduzione.

Hi @cassiawag, I'm working on it tomorrow and Sunday.
Thanks a lot for your work!

**Comment by al-epo** [comment]
Hi @cassiawag 
I would like to add the link to the italian reports of the 3rd of April and 27th of March mentioned in the report of this week. I cannot find the links in the Nextstrain website. Could you tell me how to find them? 

thank you!
Alessia

**Comment by cassiawag** [comment]
Hi Alessia, it's just the same link as in the report but replace `...sit-rep/2020...` with `...sit-rep/it/2020...`

**Comment by al-epo** [comment]
ok perfect! thank you

**Comment by cassiawag** [comment]
Just wanted to check-in on the translation? How's it going? What needs to get done in order to publish?

**Comment by sarameiqi** [comment]
Hi Cassia, 
we are waiting for @aliceLedda to check a few lines from a technical point of view. I understood that she's quite busy this week, but I would feel safer if we can wait another bit for her opinion.

Thanks a lot for all your work. I'm sharing the report with a cultural group in my hometown (via Facebook) and they really appreciate it!

**Comment by cassiawag** [comment]
So glad to hear that! I've been sharing the English versions via Facebook as well, and people seem to be really appreciating them.

**Comment by sarameiqi** [comment]
Hi all,
I gave another look at the translation and it seems clear and correct in Italian. I'm not sure whether @aliceLedda is reading us and has the time to see the translation.
If @al-epo can read it again, and it still looks good to her, maybe we can ask @cassiawag to publish it, and if Alice spots some problems later, she can push a pull request and correct it.

What do you think?

**Comment by aliceLedda** [comment]
I check in the next 15 minutes!
I have been so busy I forgot!
Alice

**Comment by aliceLedda** [comment]
Sara ho committato...  che facciamo?
Alice

**Comment by al-epo** [comment]
Ciao! 
Per me è ok

**Comment by aliceLedda** [comment]
Ok fatto allora!

**Comment by aliceLedda** [comment]
Scusate per il ritardo, e' stata una settimana impegnativa!

**Comment by sarameiqi** [comment]
@aliceLedda tranquilla, me l'ero immaginato!
Alice, if it's ok with you, we can ask @cassiawag to publish the Italian translation!

**Comment by aliceLedda** [comment]
Yes! Fine!

**Comment by cassiawag** [comment]
Trying to troubleshoot preview, but will get this published after I sort that out.

**Comment by cassiawag** [comment]
Published and tweeted: https://nextstrain.org/narratives/ncov/sit-rep/it/2020-04-24

Thank you!!!
