### ISSUE TITLE
Translate April 24 covid report into Greek

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#90]
Hello @nextstrain/greek!

The situation report from 2020-04-24 is ready to be translated to Greek. The report focuses on Africa. We chose this region this week as the outbreaks in African nations are very important to understand and do not seem to be getting a lot of press. Please translate the Twitter post below! It is a bummer when the translation is great, but people do not know that because I used Google translate for the Twitter post.

Branch to translate on: `sit-rep_el`

File to translate: https://github.com/nextstrain/translations/blob/sit-rep_el/narratives/translations_ncov_sit-rep_el_2020-04-24.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!

Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_el/ncov/sit-rep/el/2020-04-24

Twitter post to translate:
“We focus on Africa this week in our #COVID19 situation report. The report is now available in Greek. Thank you @, @, and @ for the rapid translation."

**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7

Please assign yourself to the translation if you’re working on it this week.

When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it!

Discussion board for your team is here: https://github.com/orgs/nextstrain/teams/greek

**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`.

Please add your name under `translators:` with new line, tab, and dash, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.

Note: You may know of other great resources available in Greek; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.

At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.

Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.

**Thank you all so, so much! :)**

**Comment by ghost** [comment]
Hi @akifoss can you please review latest commits. I have kept also the English part on new parts as we did last time. Feel free to delete them after your review. Thanks

**Comment by ghost** [comment]
Twitter post to translate:
“Αυτή την εβδομάδα η #COVID19 αναφορά κατάστασης καλύπτει την επιδημία στην Αφρική. Η αναφορά είναι τώρα διαθέσιμη στα Ελληνικά. Ευχαριστούμε @akifoss και @codergr για τη γρήγορη μετάφραση."

**Comment by akifoss** [comment]
Thank you very much @codergr ! 
@cassiawag the report is ready for publication :)

**Comment by cassiawag** [comment]
Published and tweeted: https://nextstrain.org/narratives/ncov/sit-rep/el/2020-04-24

Thank you!
