### ISSUE TITLE
Translate April 24 covid report into Korean

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#91]
Hello @nextstrain/korean!

The situation report from 2020-04-24 is ready to be translated to Korean. The report focuses on Africa. We chose this region this week as the outbreaks in African nations are very important to understand and do not seem to be getting a lot of press. Please translate the Twitter post below! It is a bummer when the translation is great, but people do not know that because I used Google translate for the Twitter post.

Branch to translate on: `sit-rep_ko`

File to translate: https://github.com/nextstrain/translations/blob/sit-rep_ko/narratives/translations_ncov_sit-rep_ko_2020-04-24.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!

Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_ko/ncov/sit-rep/ko/2020-04-24

Twitter post to translate:
“We focus on Africa this week in our #COVID19 situation report. The report is now available in Korean. Thank you @, @, and @ for the rapid translation."

**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7

Please assign yourself to the translation if you’re working on it this week.

When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it!

Discussion board for your team is here: https://github.com/orgs/nextstrain/teams/korean

**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`.

Please add your name under `translators:` with new line, tab, and dash, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.

Note: You may know of other great resources available in Korean; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.

At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.

Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.

**Thank you all so, so much! :)**

**Comment by taehoonh** [comment]
Hi @nextstrain/korean ,

The 04-24 report translation was complete. Please review the work. Thank you in advance.

Best,
TH

**Comment by mnkykm** [comment]
Hi everyone, I'm a bit sick and can't do the job now. Sorry.

Minkyu

**Comment by cassiawag** [comment]
I'm sorry you're sick :( Hope you heal quickly, @minkyuxyz 

@hanbin973, @kyobinkang would either of you be available to review this week?

**Comment by KyobinKang** [comment]
@cassiawag I'll go through it very soon.

**Comment by KyobinKang** [comment]
Proofreading done. I think it is ready to be published.

**Comment by cassiawag** [comment]
Published: https://nextstrain.org/narratives/ncov/sit-rep/ko/2020-04-24 !

Thanks so much all! Does anyone want to translate the twitter post?

"We focus on Africa this week in our #COVID19 situation report. The report is now available in Korean. Thank you @taeh00nha and @kyobinkang for the rapid translation."

**Comment by KyobinKang** [comment]
@cassiawag It can be translated into "이번주의 #COVID19 상황 보고서는 아프리카에 초점을 맞췄습니다. 이제 한국어로도 제공됩니다: [link] 신속한 번역을 도와주신 
@taeh00nha, @KyobinKang 님께 감사드립니다."

**Comment by cassiawag** [comment]
Thank you very much!

**Comment by taehoonh** [comment]
Hi @cassiawag,

Hope you are doing well. I just found some errors on the 04-24 report and corrected them. I would appreciate it if you merge with master branch. Thank you in advance.

Best,
TH

**Comment by cassiawag** [comment]
Hi TH,
I'm not seeing the changes you made? Are they on the `sit-rep_ko` branch? The last changes I'm seeing on the 04-24 report were mine.

**Comment by taehoonh** [comment]
Hi @cassiawag,
My bad. I had a sync issue. Sorry for making you confused. Thanks.

**Comment by cassiawag** [comment]
Updated! Thanks @taehoonh!
