### ISSUE TITLE
Translate April 24 covid report into Japanese

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#92]
Hello @nextstrain/japanese!

The situation report from 2020-04-24 is ready to be translated to Japanese. The report focuses on Africa. We chose this region this week as the outbreaks in African nations are very important to understand and do not seem to be getting a lot of press. Please translate the Twitter post below! It is a bummer when the translation is great, but people do not know that because I used Google translate for the Twitter post.

Branch to translate on: `sit-rep_ja`

File to translate: https://github.com/nextstrain/translations/blob/sit-rep_ja/narratives/translations_ncov_sit-rep_ja_2020-04-24.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!

Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_ja/ncov/sit-rep/ja/2020-04-24

Twitter post to translate:
“We focus on Africa this week in our #COVID19 situation report. The report is now available in Japanese. Thank you @, @, and @ for the rapid translation."

**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7

Please assign yourself to the translation if you’re working on it this week.

When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it!

Discussion board for your team is here: https://github.com/orgs/nextstrain/teams/japanese

**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`.

Please add your name under `translators:` with new line, tab, and dash, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.

Note: You may know of other great resources available in Japanese; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.

At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.

Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.

**Thank you all so, so much! :)**

**Comment by tomoyuki-nezu** [comment]
Hello again.
I'll translate a little. If someone have possibilities, please start with in Senegal section.

**Comment by satotake** [comment]
done @tomoyuki-nezu 

By the way, did you delete the last week report `narratives/translations_ncov_sit-rep_ja_2020-04-17.md` in [this commit](https://github.com/nextstrain/translations/commit/501ca111a416ee62185d041f7c1de67f45580451) ?
I'm wondering why

**Comment by tomoyuki-nezu** [comment]
Just un-tracked it, has it been removed? I'll add and commit again soon.

**Comment by tomoyuki-nezu** [comment]
@satotake 
Backed the files from last week.
I pulled satotake's update and merged it, and then committed again it, but it seems that it has not been reflected of satotake's translate. Could you merge and commite again on the satotake-san side?

**Comment by tomoyuki-nezu** [comment]
@satotake
Backed the files of last week report.
I pulled satotake's update and merged it, and then committed again it, but it seems that it has not been reflected of satotake's translate. Could you merge and commite again on the satotake-san side?

**Comment by satotake** [comment]
done! 👍 @tomoyuki-nezu

**Comment by tomoyuki-nezu** [comment]
I have more time at night so I will do any task.

**Comment by tomoyuki-nezu** [comment]
@satotake Could you do the merge again with the part of translated by satotake-san? I think it's my mistake, the original English text of after Senegal section is remained even when I pull it.

**Comment by satotake** [comment]
I'm sorry but I found that I have been editing `narratives/translations_ncov_sit-rep_2020-04-24.md` (not Japanese ver). 
- Recovered original file `narratives/translations_ncov_sit-rep_2020-04-24.md`.
- Updated 0424 ja file (Senegal~)

Thank you for your notification @tomoyuki-nezu

**Comment by tomoyuki-nezu** [comment]
@satotake Thank you!!! I changed only the country name (Unification).

@fzhang12 Please proofreading it.

**Comment by tomoyuki-nezu** [comment]
@satotake Thank you!!!
I changed only the country name (Unification) and The country name of the Senegal section title was "Congo", so I changed to Senegal.

@fzhang12 Please proofreading it.

**Comment by fzhang12** [comment]
Thanks for your hard work this week. Here is my feedback:
* Some of the links are fixed in the file. Please do not change round brackets next time.
* The content itself is not changed so much but i did add 1 or 2 sentences that were forgot to translate.
* Numbers of date and single digits are changed to full-length japanese version in order to increase fluency.
* change 伝搬 to 伝播

> Twitter post to translate:
> “We focus on Africa this week in our #COVID19 situation report. The report is now available in Japanese. Thank you @, @, and @ for the rapid translation."

今週の #COVID19 #新型コロナウィルス の状況報告はアフリカに注目します。
こちらから日本語でもご覧頂けるようになりました。
迅速な翻訳を行って頂いた @tommy_nezy さん、Takeshi Sato さんと @fengjun_zhang さんに感謝します。

**Comment by cassiawag** [comment]
Published and tweeted: https://nextstrain.org/narratives/ncov/sit-rep/ja/2020-04-24

Thank you Japanese team -- always a pleasure to work with you all!
