### ISSUE TITLE
Translate April 24 covid report into Mandarin Chinese

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#93]
Hello @nextstrain/mandarin!

The situation report from 2020-04-24 is ready to be translated to Mandarin. The report focuses on Africa. We chose this region this week as the outbreaks in African nations are very important to understand and do not seem to be getting a lot of press. Please translate the Twitter post below! It is a bummer when the translation is great, but people do not know that because I used Google translate for the Twitter post.

Branch to translate on: `sit-rep_zh`

File to translate: https://github.com/nextstrain/translations/blob/sit-rep_zh/narratives/translations_ncov_sit-rep_zh_2020-04-24.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!

Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_zh/ncov/sit-rep/zh/2020-04-24

Twitter post to translate:
“We focus on Africa this week in our #COVID19 situation report. The report is now available in Mandarin. Thank you @, @, and @ for the rapid translation."

**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7

Please assign yourself to the translation if you’re working on it this week.

When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it!

Discussion board for your team is here: https://github.com/orgs/nextstrain/teams/mandarin

**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`.

Please add your name under `translators:` with new line, tab, and dash, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.

Note: You may know of other great resources available in Mandarin; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.

At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.

Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.

**Thank you all so, so much! :)**

**Comment by lxy0107** [comment]
Hi all, I'm starting now

**Comment by lxy0107** [comment]
Hi all, I'm taking a pause now. Already committed for the part I finished.

**Comment by lxy0107** [comment]
Hi all, it's ready for proofreading!:)

**Comment by fzhang12** [comment]
thanks @lxy0107 ! Excellent work again this week !! 👍🏻
My feedback:
* add space between ENG and CHN
* text 5: correction of data back to original one in text 5
* text 10: modify translation of sparks

**Comment by fzhang12** [comment]
> Twitter post to translate:
> “We focus on Africa this week in our #COVID19 situation report. The report is now available in Mandarin. Thank you @, @, and @ for the rapid translation."

本周的 #COVID19 状况报告将聚焦非洲疫情。
中文翻译现已上线。
感谢 @3Xueying 和 @fengjun_zhang 对这周报告的及时高效翻译。

**Comment by cassiawag** [comment]
Published and tweeted: https://nextstrain.org/narratives/ncov/sit-rep/zh/2020-04-24

Thank you so much!! Take care.
