### ISSUE TITLE
Translate April 24 covid report into Russian

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#95]
Hello @nextstrain/russian!

The situation report from 2020-04-24 is ready to be translated to Russian. The report focuses on Africa. We chose this region this week as the outbreaks in African nations are very important to understand and do not seem to be getting a lot of press. Please translate the Twitter post below! It is a bummer when the translation is great, but people do not know that because I used Google translate for the Twitter post.

Branch to translate on: `sit-rep_ru`

File to translate: https://github.com/nextstrain/translations/blob/sit-rep_ru/narratives/translations_ncov_sit-rep_ru_2020-04-24.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!

Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_ru/ncov/sit-rep/ru/2020-04-24

Twitter post to translate:
“We focus on Africa this week in our #COVID19 situation report. The report is now available in Russian. Thank you @, @, and @ for the rapid translation."

**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7

Please assign yourself to the translation if you’re working on it this week.

When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it!

Discussion board for your team is here: https://github.com/orgs/nextstrain/teams/russian

**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`.

Please add your name under `translators:` with new line, tab, and dash, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.

Note: You may know of other great resources available in Russian; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.

At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.

Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.

**Thank you all so, so much! :)**

**Comment by irina95511** [comment]
Hi @dtaliun, @frogtraveler, @vpuller, hope you are all well! I have finished the translation, may I ask one of you to proofread? Many thanks in advance! 

Hi @cassiawag, russian translation is ready for proofreading however I could not find a box on the 'Translation' page to move it to 'Ready for proofreading/reviewing' section...

**Comment by irina95511** [comment]
@cassiawag sorry, forgot to translate Twitter post! Please, find below.

"На этой неделе наш ситуационный отчет посвящен распространению #COVID19 в Африке. Отчет теперь доступен на русском языке. Спасибо @, @ и @ за быстрый перевод."

**Comment by cassiawag** [comment]
Thanks @irina95511. I've updated it :) Thanks for the hard work!

**Comment by irina95511** [comment]
@cassiawag thank you, that was an interesting text to work on :)

**Comment by frogtraveler** [comment]
@irina95511 I'll review. Thank you for translation! Sorry I couldnt chime in this time

**Comment by frogtraveler** [comment]
@irina95511 Thank you for translating the document this week! Only few minor changes from me. I've changed the status to ready for publication. 

@cassiawag It might be better if in the report the link on "How to read a phylogenetic tree" leads to a version of the document in Russian. It points to the English version right now.

**Comment by cassiawag** [comment]
Thanks @irina95511 & @frogtraveler for the translation. I got the links fixed to the correct ones and published the translation: https://nextstrain.org/narratives/ncov/sit-rep/ru/2020-04-24

Take care!
