### ISSUE TITLE
Translate April 24 covid report into Spanish

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#96]
Hello @nextstrain/spanish!

The situation report from 2020-04-24 is ready to be translated to Spanish. The report focuses on Africa. We chose this region this week as the outbreaks in African nations are very important to understand and do not seem to be getting a lot of press. Please translate the Twitter post below! It is a bummer when the translation is great, but people do not know that because I used Google translate for the Twitter post.

Branch to translate on: `sit-rep_es`

File to translate: https://github.com/nextstrain/translations/blob/sit-rep_es/narratives/translations_ncov_sit-rep_es_2020-04-24.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!

Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_es/ncov/sit-rep/es/2020-04-24

Twitter post to translate:
“We focus on Africa this week in our #COVID19 situation report. The report is now available in Spanish. Thank you @, @, and @ for the rapid translation."

**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7

Please assign yourself to the translation if you’re working on it this week.

When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it!

Discussion board for your team is here: https://github.com/orgs/nextstrain/teams/spanish

**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`.

Please add your name under `translators:` with new line, tab, and dash, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.

Note: You may know of other great resources available in Spanish; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.

At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.

Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.

**Thank you all so, so much! :)**

**Comment by doyarzun00** [comment]
Sorry folks this weekend I'm not available due to monday deadline...

**Comment by cassiawag** [comment]
@msaavedra1026 is going to join the Spanish translations team! Thank you so much -- we're really happy to have your help. I've invited you to join the Nextstrain translators team; you'll need to accept my invitation, and then you should have access to push to `sit-rep_es`.

All of the information you need for the translation should be above. But please ask any questions. If you can work on the first draft of the translation, one of the other translators (who all have backgrounds in phylogenetics) can proof the translation. If there's some technical parts that you're unsure of how to translate, feel free to leave them for the other translators. It would also be nice if you through a few of the previous Spanish reports to get a sense of translation style.

Thank you again!

**Comment by miparedes** [comment]
Hey all! happy to start it off this week. I can do the first half (through "Two local transmission chains in Kinshasa, seeded in early March") if someone can pick up the second half after that. Hope everyone is staying safe and @msaavedra1026 Welcome to the team!

**Comment by miparedes** [comment]
Hey all, sorry for the delay! The first half is translated and has been pushed!

**Comment by cassiawag** [comment]
Thanks for the translation, Miguel! @Cholokiwi or @msaavedra1026, would either of you be able to do the 2nd half?

**Comment by Cholokiwi** [comment]
Hi @cassiawag and all,
I'll do the second part. Sofia, would you like to do the proofreading to get you familiar with the translations? BTW, somehow I can't tag you here @msaavedra1026
Cheers,

Roy

**Comment by Cholokiwi** [comment]
Hi all,
Translation is ready for proofreading.

Roy

**Comment by cassiawag** [comment]
Fantastic. I've been having trouble getting ahold of Sofia, and I'm not sure she'll respond. @miparedes & @Cholokiwi, can you both proof the other's translation?

Thanks so much! I will try to be better organized this upcoming week.

**Comment by Cholokiwi** [comment]
Sounds good Cassia. Let’s do that.
Cheers,
Roy

**Comment by miparedes** [comment]
@cassiawag @Cholokiwi Just finished proofreading the second part that Roy did -- very minor edits.

**Comment by Cholokiwi** [comment]
Hi @cassiawag , 
Report is ready now, same a couple of minor edits only.

**Comment by Cholokiwi** [comment]
... and the twitter post:
"Esta semana nos enfocamos en África en el reporte de la situación del COVID19. El reporte esta disponible en español. Gracias @miparedes y @Cholokiwi por la traducción."

**Comment by cassiawag** [comment]
Thank you Roy & Miguel! Really appreciate you both. I'll get this published

**Comment by cassiawag** [comment]
Published and tweeted: https://nextstrain.org/narratives/ncov/sit-rep/es/2020-04-24?f_region=Africa

Thank you!!
