### ISSUE TITLE
Translate April 24 covid report into Portuguese

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#99]
Hello @nextstrain/portuguese!

The situation report from 2020-04-24 is ready to be translated to Portuguese. The report focuses on Africa. Please chime in if you're able to review the translation. I would hate for @7glaucio to translate the report, but for it not to get published because nobody could review it. Also, if you have any suggestions for another Brazil Portuguese speaker who's got a background phylogenetics who could help review translations, that would be much appreciated!

Please translate the Twitter post below! It is a bummer when the translation is great, but people do not know that because I used Google translate for the Twitter post.

Branch to translate on: `sit-rep_pt`

File to translate: https://github.com/nextstrain/translations/blob/sit-rep_pt/narratives/translations_ncov_sit-rep_pt_2020-04-24.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!

Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_pt/ncov/sit-rep/pt/2020-04-24

Twitter post to translate:
“We focus on Africa this week in our #COVID19 situation report. The report is now available in Portuguese. Thank you @, @, and @ for the rapid translation."

**Logistics**
Please update the translations board as you work on the translation: https://github.com/orgs/nextstrain/projects/7

Please assign yourself to the translation if you’re working on it this week.

When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it!

Discussion board for your team is here: https://github.com/orgs/nextstrain/teams/portuguese

**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`.

Please add your name under `translators:` with new line, tab, and dash, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.

Note: You may know of other great resources available in Portuguese; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.

At minimum, I require two sets of eyes on every translation; one of those people should have a background in phylogenetics. Although if you have more, that’s fine too.

Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.

**Thank you all so, so much! :)**

**Comment by 7glaucio** [comment]
I gonna wait until somebody shows up willing to review. Let me know, then I will translate it right away.

**Comment by cassiawag** [comment]
Working on finding some more people too. I'll let you know!

**Comment by andersonbrito** [comment]
@7glaucio, please go ahead and I'll cover the review role this week.

I've reached out to some colleagues to check if they know someone with the expected expertise/availability, willing to help in a regular basis. I'll let you know if I get any positive response.

**Comment by 7glaucio** [comment]
@andersonbrito All set. It's good to go! The reports focused on continents have been quite short lately. I think you won't have any problem proofreading it quickly.

**Comment by andersonbrito** [comment]
Hey,
The final version is now committed. Thank you for the hard work, @7glaucio.

I managed to contact colleagues from two research groups in Brazil. A colleague from Brasília (Miguel) is willing to help on the next version, and is ready to get on board ASAP. I'm just waiting for his GitHub handle.

I guess if we get one or two more people on board, we can work in shifts, translating or reviewing the narratives according to our availability in that specific week.

If the report 2020-04-17 is already translated, only pending revision, we could ask a new member to have a go, and familiarize with the translation system/process.

Let me know your thoughts.

**Comment by cassiawag** [comment]
Thanks @andersonbrito; I think that sounds like a good suggestion forward. Let me know when you have his GitHub, and I'll add him to the team.

Thanks for the translation both of you @7glaucio & @andersonbrito. The report is now published and tweeted: https://nextstrain.org/narratives/ncov/sit-rep/pt/2020-04-24
